### ISSUE TITLE
Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database while I execute the following query

### ISSUE THREAD

**Issue by rmgpinto** [neo4j/neo4j#12030]
I'm getting `Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database while I execute the following query`:

```
USING PERIODIC COMMIT
LOAD CSV WITH HEADERS FROM "file:///u_t.csv" AS row
MATCH (u:User), (t:Topic)
WHERE u.id = row.user_id AND t.id = row.topic_id
MERGE (u)-[:INTERESTED_IN]->(t);
```

```
$ QUERY='USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:///u_t.csv" AS row MATCH (u:User), (t:Topic) WHERE u.id = row.user_id AND t.id = row.topic_id MERGE (u)-[:INTERESTED_IN]->(t);'
$ /var/lib/neo4j/bin/cypher-shell -a $NEO4J_ADDRESS -p 7687 --format plain \"$QUERY\"
```

The file has only 54595 rows.
The the `cypher-shell` process exits, but the rows continue to be loaded.
I was expecting the `cypher-shell` to be blocked until the data load was completed.

- Neo4j version: 3.4.5-enterprise (Docker)
- Operating system: AWS AMI Linux
- API/Driver: Cypher Shell

**Comment by rmgpinto** [comment]
This issue only happens when connecting remotely, if I use the `cypher-shell` from the neo4j node it loads all the data correctly.
My suspicion is that `cypher-shell` does not have a TCP Keep Alive (like SSH).

**Comment by SaschaPeukert** [comment]
Hej @rmgpinto ,

Thanks for reporting. We will have a look at it!

**Comment by pricklywiggles** [comment]
Any news on this?

**Comment by sherfert** [comment]
@pricklywiggles @rmgpinto 
This was fixed in 3.5 quite a while ago, but we forgot to close the issue. Can you please verify on a recent 3.5 version that you don't get this error any more?

**Comment by Hajerinspirations** [comment]
I still get the same error. I tested this morning with the version 3.5.14.

**Comment by zhenlineo** [comment]
There is something in your dev env that kills the connections between server and driver. It is not the driver or server not want to keep the socket alive. It is likely some firewall settings that kills long running connections when there is no application message, which `socket_keep_alive` will not really help in this case. If you query is a long running cypher query without any return for a long time, then this connection could be killed by your container/platform etc.

May I ask if it is true that your queries are long running queries?

To avoid long running queries being killed, here are some actions you can try:
1) Enlarge your container/platform (idle) socket timeout.
2) Put your long running queries into two procedures. One to start the query, another to query the procedure result.

Cheers,
Zhen

**Comment by zhaklinab** [comment]
I have version 3.5.14 of neo4j and I am experiencing the same error when I try to pull the neo4j image in a docker container.

**Comment by JLT032** [comment]
Same issue connecting from dbeaver to neo4j on localhost over jdbc/bolt

**Comment by theethicalcoder81** [comment]
Hi I am getting this error "Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database", while I am trying to set up the database plugin to export a model from Archimate into Neo4j. Any ideas on how I can go about troubleshooting this ?

**Comment by Tin-Nguyen** [comment]
I'm getting this error from Neo4j Sink Connector, the connector task stopped working after that `Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database`
Neo4j: 3.5.14

**Comment by nghiahhnguyen** [comment]
I'm having this issue as well when my query is running for too long.

**Comment by beingsagir** [comment]
I am getting this issue too.

**Comment by nghiahhnguyen** [comment]
> I'm having this issue as well when my query is running for too long.

For what it's worth, I am reporting the cause of my issue. Because my query was using too much memory, my server ran out of memory, and `neo4j` is killed. I know this might not be true for everyone, but you can try and check if you are facing the same scenario.

I fixed it by using [periodic commits](https://neo4j.com/docs/labs/apoc/current/graph-updates/periodic-execution/).

**Comment by technige** [comment]
These will likely be fixed by the opt-in NOOP message introduced in 4.1.

**Comment by Meatballs1** [comment]
Having to do a upgrade to 4.1 is a big leap due to the cypher driver support. Is there a workaround for 3.5? Mine is just doing a CSV import and its terminating even after a few seconds.

**Comment by advaitkulkarni8** [comment]
Do we know what is going on with this error? I continue to get this issue almost everyday. None of the solutions like Java driver version, SSH removal (https) or reducing the amount of data seemed to be working
