### ISSUE TITLE
Exporting a subgraph with full-text index on relationships

### ISSUE THREAD

**Issue by conker84** [neo4j/neo4j#12304]
- Neo4j version: 3.5
- Operating system: Mac

### Steps to reproduce

```
    @Test
    public void testExportFullTextIndex()
    {
        gdb.execute( "CALL db.index.fulltext.createRelationshipIndex('MyCoolRelFulltextIndex', ['REL'], ['rel_value'])").close();
        gdb.schema().indexFor( Label.label( "Foo" ) ).on( "bar" ).create();
        assertEquals( "create index on :`Foo`(`bar`);" + lineSeparator() , doExportGraph( gdb ) );
    }
```

### Expected behaviour

The `SubGraph` class should export the index.

### Actual behaviour

Throws the following exception:
```
java.lang.IllegalStateException: This is not a node index.

	at org.neo4j.kernel.impl.coreapi.schema.IndexDefinitionImpl.assertIsNodeIndex(IndexDefinitionImpl.java:326)
	at org.neo4j.kernel.impl.coreapi.schema.IndexDefinitionImpl.getLabels(IndexDefinitionImpl.java:95)
	at org.neo4j.cypher.export.SubGraphExporter.exportIndexes(SubGraphExporter.java:104)
	at org.neo4j.cypher.export.SubGraphExporter.appendIndexes(SubGraphExporter.java:185)
	at org.neo4j.cypher.export.SubGraphExporter.export(SubGraphExporter.java:60)
	at org.neo4j.cypher.export.SubGraphExporter.export(SubGraphExporter.java:54)
	at org.neo4j.cypher.export.ExportTest.doExportGraph(ExportTest.java:109)
	at org.neo4j.cypher.export.ExportTest.doExportGraph(ExportTest.java:103)
	at org.neo4j.cypher.export.ExportTest.testExportIndex(ExportTest.java:247)
```

**Comment by klaren** [comment]
It should be fixed by #12338 and will be in the next 3.5 release.

Thank you for reporting this!

**Comment by a-pagano** [comment]
Hi, 
We've installed the latest 3.5.X release (3.5.18) along with the latest apoc-all release (3.5.0.11) and it seems that this is still a problem:

assuming a fulltext relation index on `REL_TYPE` relations:

`MATCH p=(p1:Label1)<-[r:REL_TYPE]-(p2:Label2)
WITH collect(p1) + collect(p2) as collected_nodes, collect(r) as collected_rels
CALL apoc.export.cypher.data(collected_nodes,collected_rels,'/tmp/export.cypher',{format:'cypher-shell'}) YIELD file, source, format, nodes, relationships, properties, time
RETURN nodes, relationships, time;`

raises:

`Failed to invoke procedure 'apoc.export.cypher.data': Caused by: java.lang.IllegalStateException: This is not a node index.`

**Comment by alizadehei** [comment]
Hi,
We've installed the 4.2.0.4 release and it seems that this is still a problem:

> Failed to invoke procedure 'apoc.export.cypher.all' : Caused by: java.lang.IllegalStateException: This is not a node index.
