### ISSUE TITLE
4.0.0 enterprise cluster becomes irreparably corrupt from working 3.5 statement

### ISSUE THREAD

**Issue by chrisdostert** [neo4j/neo4j#12402]
- Neo4j version: 4.0.0
- Operating system: `neo4j:4.0.0-enterprise`docker image 
- API/Driver: cypher

I'm still trying to narrow down the exact repro but a cypher create/merge statement that was working in 3.5, caused our prod cluster to become corrupt in 4.0. 

The cluster had been migrated from 3.5.12 a few weeks ago and running reliably until this particular statement was run (it's an infrequently run statement), which brought down and corrupted the entire cluster with logs:
```
ERROR Clustering components for database 'neo4j' have encountered a critical error org.neo4j.internal.kernel.api.exceptions.TransactionFailureException: Could not apply the transaction to the store after written to log
```
```
java.lang.RuntimeException: org.neo4j.internal.kernel.api.exceptions.TransactionFailureException: Could not apply the transaction to the store after written to log
	at com.neo4j.causalclustering.core.state.machines.token.ReplicatedTokenStateMachine.applyToStore(ReplicatedTokenStateMachine.java:96)
	at com.neo4j.causalclustering.core.state.machines.token.ReplicatedTokenStateMachine.applyCommand(ReplicatedTokenStateMachine.java:74)
	at com.neo4j.causalclustering.core.state.machines.CoreStateMachines$StateMachineCommandDispatcher.dispatch(CoreStateMachines.java:119)
	at com.neo4j.causalclustering.core.state.machines.token.ReplicatedTokenRequest.dispatch(ReplicatedTokenRequest.java:94)
	at com.neo4j.causalclustering.core.state.CommandApplicationProcess.handleOperations(CommandApplicationProcess.java:234)
	at com.neo4j.causalclustering.core.state.CommandApplicationProcess.applyBatch(CommandApplicationProcess.java:210)
	at com.neo4j.causalclustering.core.state.CommandBatcher.flush(CommandBatcher.java:44)
	at com.neo4j.causalclustering.core.state.CommandApplicationProcess.applyUpTo(CommandApplicationProcess.java:175)
	at com.neo4j.causalclustering.core.state.CommandApplicationProcess.applyJob(CommandApplicationProcess.java:139)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.neo4j.internal.kernel.api.exceptions.TransactionFailureException: Could not apply the transaction to the store after written to log
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:82)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
	at com.neo4j.causalclustering.core.state.machines.StateMachineCommitHelper.commit(StateMachineCommitHelper.java:56)
	at com.neo4j.causalclustering.core.state.machines.StateMachineCommitHelper.commit(StateMachineCommitHelper.java:51)
	at com.neo4j.causalclustering.core.state.machines.token.ReplicatedTokenStateMachine.applyToStore(ReplicatedTokenStateMachine.java:92)
	... 9 more
Caused by: org.neo4j.internal.kernel.api.exceptions.TransactionApplyKernelException: Failed to apply transaction: Transaction #1832889 at log position LogPosition{logVersion=1, byteOffset=217722710} {started 1970-01-01 00:00:00.000+0000, committed 1970-01-01 00:00:00.000+0000, with 1 commands in this transaction, lease 0, latest committed transaction id when started was 0, additional header bytes: 
```
...
```
at org.neo4j.internal.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:302)
at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
... 13 more
Caused by: org.neo4j.token.api.NonUniqueTokenException: The PropertyKey NamedToken[name:stripeBankAccountId, id:611, internal:false] is not unique, it existed as NamedToken[name:__org.neo4j.SchemaRule.IndexConfig.spatial.wgs-84.max, id:611, internal:true]. at org.neo4j.token.TokenRegistry.put(TokenRegistry.java:73) at org.neo4j.token.AbstractTokenHolderBase.addToken(AbstractTokenHolderBase.java:52) at org.neo4j.internal.recordstorage.BridgingCacheAccess.addPropertyKeyToken(BridgingCacheAccess.java:68) at org.neo4j.internal.recordstorage.CacheInvalidationTransactionApplier.visitPropertyKeyTokenCommand(CacheInvalidationTransactionApplier.java:69) at org.neo4j.internal.recordstorage.Command$PropertyKeyTokenCommand.handle(Command.java:537) at org.neo4j.internal.recordstorage.TransactionApplierFacade.visit(TransactionApplierFacade.java:57) at org.neo4j.internal.recordstorage.TransactionApplierFacade.visit(TransactionApplierFacade.java:32) at org.neo4j.kernel.impl.transaction.log.PhysicalTransactionRepresentation.accept(PhysicalTransactionRepresentation.java:76) at org.neo4j.kernel.impl.api.TransactionToApply.accept(TransactionToApply.java:130) at org.neo4j.internal.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:294) ... 14 more
```

Repair was attempted by restarting the nodes but this resulted in all nodes failing to start with logs:
```
ERROR Clustering components for database 'neo4j' have encountered a critical error Encountered error when attempting to reconcile database neo4j from state 'EnterpriseDatabaseState{databaseId=DatabaseId{name='neo4j', databaseId=DatabaseIdWithoutName{uuid=9f35bdfb-46ba-40f8-a292-88b0ba533c55}}, operatorState=STOPPED, failed=false}' to state 'online'
```

```
java.lang.IllegalStateException: Encountered error when attempting to reconcile database neo4j from state 'EnterpriseDatabaseState{databaseId=DatabaseId{name='neo4j', databaseId=DatabaseIdWithoutName{uuid=9f35bdfb-46ba-40f8-a292-88b0ba533c55}}, operatorState=STOPPED, failed=false}' to state 'online' at com.neo4j.dbms.DbmsReconciler.reportErrorAndPanicDatabase(DbmsReconciler.java:435) at com.neo4j.dbms.DbmsReconciler.handleReconciliationErrors(DbmsReconciler.java:420) at com.neo4j.dbms.DbmsReconciler.lambda$postReconcile$14(DbmsReconciler.java:369) at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1947) at com.neo4j.dbms.DbmsReconciler.postReconcile(DbmsReconciler.java:367) at com.neo4j.dbms.DbmsReconciler.lambda$scheduleReconciliationJob$7(DbmsReconciler.java:234) at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: org.neo4j.dbms.api.DatabaseManagementException: Unable to start database `DatabaseId{name='neo4j', databaseId=DatabaseIdWithoutName{uuid=9f35bdfb-46ba-40f8-a292-88b0ba533c55}}` at com.neo4j.dbms.database.ClusteredMultiDatabaseManager.startDatabase(ClusteredMultiDatabaseManager.java:83) at com.neo4j.dbms.database.ClusteredMultiDatabaseManager.startDatabase(ClusteredMultiDatabaseManager.java:37) at com.neo4j.dbms.database.MultiDatabaseManager.forSingleDatabase(MultiDatabaseManager.java:112) at com.neo4j.dbms.database.MultiDatabaseManager.startDatabase(MultiDatabaseManager.java:98) at com.neo4j.dbms.DbmsReconciler.start(DbmsReconciler.java:537) at com.neo4j.dbms.Transitions$TransitionFunction.lambda$prepare$0(Transitions.java:219) at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:335) at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:336) at com.neo4j.dbms.DbmsReconciler.doTransitions(DbmsReconciler.java:318) at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$9(DbmsReconciler.java:308) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ... 3 more Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.TransactionLogsRecovery@97f40fb' failed to initialize. Please see the attached cause exception "Internal token for id 611 not found.". at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:426) at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66) at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102) at org.neo4j.kernel.recovery.Recovery.performRecovery(Recovery.java:364) at org.neo4j.kernel.recovery.Recovery.performRecovery(Recovery.java:246) at org.neo4j.kernel.recovery.RecoveryFacade.recovery(RecoveryFacade.java:49) at com.neo4j.causalclustering.core.CoreDatabase.lambda$new$0(CoreDatabase.java:42) at org.neo4j.kernel.lifecycle.LifecycleAdapter$3.start(LifecycleAdapter.java:86) at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444) at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111) at com.neo4j.causalclustering.common.ClusteredDatabase.start(ClusteredDatabase.java:39) at com.neo4j.dbms.database.ClusteredMultiDatabaseManager.startDatabase(ClusteredMultiDatabaseManager.java:79) ... 13 more Caused by: java.lang.RuntimeException: Error reading transaction logs, recovery not possible. To force the database to start anyway, you can specify 'unsupported.dbms.tx_log.fail_on_corrupted_log_files=false'. This will try to recover as much as possible and then truncate the corrupt part of the transaction log. Doing this means your database integrity might be compromised, please consider restoring from a consistent backup instead. at org.neo4j.kernel.recovery.Recovery.throwUnableToCleanRecover(Recovery.java:464) at org.neo4j.kernel.recovery.TransactionLogsRecovery.init(TransactionLogsRecovery.java:147) at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:405) ... 24 more Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.internal.recordstorage.RecordStorageEngine$2@58b75fa3' failed to initialize. Please see the attached cause exception "Internal token for id 611 not found.". at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:426) at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66) at org.neo4j.kernel.recovery.TransactionLogsRecovery.init(TransactionLogsRecovery.java:117) ... 25 more Caused by: java.lang.RuntimeException: org.neo4j.internal.kernel.api.exceptions.schema.MalformedSchemaRuleException: Cannot read schema rule because it is referring to a property key token (id 611) that does not exist. at org.neo4j.internal.recordstorage.SchemaStorage.readSchemaRuleThrowingRuntimeException(SchemaStorage.java:266) at org.neo4j.internal.recordstorage.SchemaStorage.lambda$streamAllSchemaRules$5(SchemaStorage.java:238) at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) at java.base/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177) at java.base/java.util.stream.Streams$RangeLongSpliterator.tryAdvance(Streams.java:207) at java.base/java.util.Spliterator$OfLong.tryAdvance(Spliterator.java:740) at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294) at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161) at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300) at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) at org.neo4j.internal.recordstorage.SchemaCache$SchemaCacheState.load(SchemaCache.java:298) at org.neo4j.internal.recordstorage.SchemaCache$SchemaCacheState.<init>(SchemaCache.java:264) at org.neo4j.internal.recordstorage.SchemaCache.load(SchemaCache.java:134) at org.neo4j.internal.recordstorage.RecordStorageEngine.loadSchemaCache(RecordStorageEngine.java:368) at org.neo4j.internal.recordstorage.RecordStorageEngine$2.init(RecordStorageEngine.java:459) at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:405) ... 27 more Caused by: org.neo4j.internal.kernel.api.exceptions.schema.MalformedSchemaRuleException: Cannot read schema rule because it is referring to a property key token (id 611) that does not exist. at org.neo4j.kernel.impl.store.SchemaStore.insertPropertyIntoMap(SchemaStore.java:463) at org.neo4j.kernel.impl.store.SchemaStore.schemaRecordToMap(SchemaStore.java:445) at org.neo4j.kernel.impl.store.SchemaStore.readSchemaRule(SchemaStore.java:326) at org.neo4j.internal.recordstorage.SchemaStorage.readSchemaRule(SchemaStorage.java:274) at org.neo4j.internal.recordstorage.SchemaStorage.readSchemaRuleThrowingRuntimeException(SchemaStorage.java:259) ... 44 more Caused by: org.neo4j.token.api.TokenNotFoundException: Internal token for id 611 not found. at org.neo4j.token.AbstractTokenHolderBase.getInternalTokenById(AbstractTokenHolderBase.java:121) at org.neo4j.kernel.impl.store.SchemaStore.insertPropertyIntoMap(SchemaStore.java:457) ... 48 more
```
I tried starting each node as a single instance but each failed to repair the corrupt datastore and refused to start. 

I had a duplicate cluster in test environment that when I ran the same transaction failed in the identical way so this was not just a fluke. 

I will try to post more details here once I can further isolate the root cause. 

This appears to be a p0 bug in neo4j 4.0.0. 
see also https://community.neo4j.com/t/nonuniquetokenexception-cant-launch-database-cant-use-cypher-shell-to-fix-it/13551/7

**Comment by chrisdostert** [comment]
Further information so far gathered: If I run the same statement against the same restored backup but without clustering enabled it succeeds without issue.

**Comment by InverseFalcon** [comment]
Information the upgrade process would help here. 
Here is the section in the docs for the 4.0 upgrade:
https://neo4j.com/docs/operations-manual/current/upgrade/causal-cluster/#cc-upgrade-guide

This should have been an offline upgrade (no rolling upgrade support to 4.0). 

SINGLE mode should have been used for the actual upgrade part. After the upgrade is completed on the single instance, the instance should have been shut down and the store seeded to the other cluster nodes, then switched to CORE mode and the cluster started.

Please let us know if these steps were all taken. If there's any way you can share your store with us, that may help us narrow in on the issue.

**Comment by chrisvest** [comment]
Please include the complete and unedited stack traces.

In one of the stack traces on the community site, there is this message:

> Error reading transaction logs, recovery not possible. To force the database to start anyway, you can specify 'unsupported.dbms.tx_log.fail_on_corrupted_log_files=false'. This will try to recover as much as possible and then truncate the corrupt part of the transaction log. Doing this means your database integrity might be compromised, please consider restoring from a consistent backup instead.

I'm curious if you tried that. And if it didn't help, I wonder what new errors might've shown up.

**Comment by chrisdostert** [comment]
@InverseFalcon thanks, I can confirm those were the steps followed. 

@chrisvest yes I did try it individually on all 3 instances in (single mode) see attached 
[debug.log](https://github.com/neo4j/neo4j/files/4227239/debug.log)
for complete log of that failing (from startup to failure) on one of them

**Comment by chrisdostert** [comment]
Another thing possibly relevant, the statement that causes the kaboom is NOT being executed as a transaction.

**Comment by MishaDemianenko** [comment]
@chrisdostert thanks for the debub.log! Is there any way You can share transaction logs (ideally on a state where they are detected as corrupted ) with us?

**Comment by chrisdostert** [comment]
@MishaDemianenko sure thing. What's the recommended way to do that?

**Comment by chrisdostert** [comment]
`/data/transactions/neo4j` files seem to be binary format; are those what you need? Guessing they may contain sensitive information?

**Comment by MishaDemianenko** [comment]
@chrisdostert 
Correct: `/data/transactions/neo4j` is a directory that contains transaction logs for `neo4j` database.

Our transaction log files contain whole transaction changeset with additional undo, redo information.
This means that data that was part of some transaction that is present in a particular transaction log can be extracted. And if Your transactions contain/may contain some sensitive data - its better not to share that, at least over public channels.

**Comment by chrisdostert** [comment]
got it; sensitive data is present so not readily achievable unfortunately.

**Comment by chrisvest** [comment]
The debug.log has nothing on this issue. There are no stack traces or exceptions in it, and it doesn't mention the property key token  you were having problems with.

Do you have a more relevant archived log, or a log from a different instance if this is a clustered deployment. Also, how did you perform the upgrade, as in, what are the precise steps you took in upgrading your deployment from 3.5.x to 4.0.0?

**Comment by chrisdostert** [comment]
@chrisvest my mistake; I accidentally grabbed the log file of the restored node. The correct one is attached.
[debug.log](https://github.com/neo4j/neo4j/files/4232935/debug.log)

**Comment by chrisvest** [comment]
I tried recreating your scenario as described: have an existing 3.5.14 database in a cluster, with data and with some indexes. Then upgrade the cluster members to 4.0.0 (following the guides in the manual and all that jazz). Start up the cluster, and run a transaction that causes a new token to be allocated. All of this worked fine, so there must be something else going on. Perhaps it's not related to the upgrade at all, but a bug that can show up on in any 4.0.0 cluster regardless of it's history of past versions.

Here's what your new debug log is telling me, annotated with a bit of Neo4j internals deep-dive:

1. When the database starts, it notices that the store has not been cleanly shut down, for whatever reason (crash, file system snapshot, who knows). That's what this log line is about: `2020-02-20 19:49:51.780+0000 INFO [o.n.k.d.Database] [neo4j] Commits found after last check point (which is at LogPosition{logVersion=1, byteOffset=891512}). First txId after last checkpoint: 1830056`
1. Recovery is then started, and there are 3 parts to it: undo, initialise the schema, redo.
1. The reason we do it like this, is because recovery needs to update our indexes as well, but we need to read from the store in order to know what indexes we have, and we can't read from a store that isn't in a clean state. So...
1. First we undo all transactions in reverse order, back to the recovery position. Now the store should be in a clean, but old state. We don't need to undo writes to the indexes, since the redo will just overwrite whatever entries are there; index writes are idempotent, so this is fine.
1. Then, having the store in a clean state, we can initialise our schema and figure out what indexes we have, get them booted up and ready to receive updates from the redo we're about to do. This is the part that fails in the new debug log you shared.
1. Each index and constraint in our schema store is _kind of_ like a node, in that it has a bunch of properties that describe its structure. A property, as you know them on the user surface, has a name and a value. Internally, it's a property key id (an integer) and a value. The key id is the `611` number that your exceptions are talking about. These have a two-way mapping between the id and the name.
1. In the debug log, we end up reading a schema rule (it's either an index, or a constraint) that has a property with key id `611`, _but_ we can't find any mapping between that id and any name; that's the `TokenNotFoundException`. This means we can't actually read this schema rule, and an exception is thrown. That's the `MalformedSchemaRuleException`.
1. This exception bubbles out of recovery, and the `neo4j` database fails to start. As part of this, the transaction log position is reset to the location of the last transaction that we _could_ recover. Since we only managed to finish the undo part of the recovery, this ends up being the beginning of the checkpoint.
1. Then there's a separate thing about a `NullPointerException` in `IndexStatisticsStore`. This most likely happened because we didn't finish initialising the schema.
1. At any rate, because we can't initialise our schema -- it throws an exception -- it means we can't start the database.

One thing that is not clear from this bug report, is whether this recovery episode in the debug log happened first, or if the `NonUniqueTokenException` you posted originally, happened first. It would be good to get that clarified before speculating further.

**Comment by chrisdostert** [comment]
Thanks, the logs initially posted including the “NonUniqueTokenException” happened first. Those were the cluster changing from healthy to heart attack. The debug.log uploaded later was Re: what I got when trying to restart with 'unsupported.dbms.tx_log.fail_on_corrupted_log_files=false'.

**Comment by chrisvest** [comment]
@chrisdostert Okay. Do you have the debug log that contains the original `NonUniqueTokenException`? There's nothing in the log you linked in your earlier [comment](https://github.com/neo4j/neo4j/issues/12402#issuecomment-588428561).

**Comment by chrisdostert** [comment]
I don’t unfortunately. Only what was included in the initial issue (which was from  stdout/stderr not debug.log)

**Comment by chrisdostert** [comment]
The cluster was running in kubernetes so debug.log was ephemeral

**Comment by victorenator** [comment]
I have a similar issue with a single community server 4.0.1.
I run the statement that creates a new property `size`:
```cql
MATCH (doc:Document {id: 'doc1'}) SET doc.size = 12000
```

I get the error:
```
org.neo4j.token.api.NonUniqueTokenException: The PropertyKey NamedToken[name:size, id:133, internal:false] is not unique, it existed as NamedToken[name:__org.neo4j.SchemaRule.IndexConfig.spatial.wgs-84.max, id:133, internal:true].
```

Debug log:
```
2020-03-04 10:09:25.591+0000 ERROR [o.n.b.r.s.i.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Newly created token should be unique., reference 44ec2338-9fa2-4687-b631-660ed04b5245.
2020-03-04 10:09:25.592+0000 ERROR [o.n.b.r.s.i.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Newly created token should be unique., reference 44ec2338-9fa2-4687-b631-660ed04b5245. Newly created token should be unique.
org.neo4j.kernel.impl.query.QueryExecutionKernelException: Newly created token should be unique.
        at org.neo4j.bolt.runtime.statemachine.impl.AbstractTransactionStateMachineSPI$AbstractBoltResultHandle.start(AbstractTransactionStateMachineSPI.java:140)
        at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:534)
        at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State$2.run(TransactionStateMachine.java:330)
        at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine.run(TransactionStateMachine.java:82)
        at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine.run(TransactionStateMachine.java:75)
        at org.neo4j.bolt.v4.runtime.InTransactionState.processRunMessage(InTransactionState.java:81)
        at org.neo4j.bolt.v4.runtime.InTransactionState.processUnsafe(InTransactionState.java:48)
        at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
        at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.nextState(AbstractBoltStateMachine.java:143)
        at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.process(AbstractBoltStateMachine.java:91)
        at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:90)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.lambda$enqueue$0(DefaultBoltConnection.java:151)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatchInternal(DefaultBoltConnection.java:240)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:175)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:165)
        at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:212)
        at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:195)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: Newly created token should be unique.
        at org.neo4j.bolt.runtime.statemachine.impl.BoltAdapterSubscriber.assertSucceeded(BoltAdapterSubscriber.java:104)
        at org.neo4j.bolt.runtime.statemachine.impl.AbstractTransactionStateMachineSPI$AbstractBoltResultHandle.start(AbstractTransactionStateMachineSPI.java:134)
        ... 21 more
Caused by: org.neo4j.exceptions.CypherExecutionException: Newly created token should be unique.
        at org.neo4j.cypher.internal.planning.ExceptionTranslationSupport.translateException(ExceptionTranslationSupport.scala:41)
        at org.neo4j.cypher.internal.planning.ExceptionTranslationSupport.translateException$(ExceptionTranslationSupport.scala:32)
        at org.neo4j.cypher.internal.planning.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:40)
        at org.neo4j.cypher.internal.planning.ExceptionTranslatingQueryContext.getOrCreatePropertyKeyId(ExceptionTranslatingQueryContext.scala:95)
        at org.neo4j.cypher.internal.runtime.interpreted.DelegatingQueryContext.getOrCreatePropertyKeyId(DelegatingQueryContext.scala:112)
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.AbstractSetPropertyOperation.setProperty(SetOperation.scala:70)
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.SetEntityPropertyOperation.set(SetOperation.scala:99)
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.SetPipe.$anonfun$internalCreateResults$1(SetPipe.scala:32)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:455)
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:29)
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:70)
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:66)
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:60)
        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:88)
        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.initiate(StandardInternalExecutionResult.scala:51)
        at org.neo4j.cypher.internal.result.ClosingExecutionResult.$anonfun$initiate$1(ClosingExecutionResult.scala:55)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at org.neo4j.cypher.internal.result.ClosingExecutionResult.safely(ClosingExecutionResult.scala:90)
        at org.neo4j.cypher.internal.result.ClosingExecutionResult.initiate(ClosingExecutionResult.scala:55)
        at org.neo4j.cypher.internal.result.ClosingExecutionResult$.wrapAndInitiate(ClosingExecutionResult.scala:179)
        at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.innerExecute(CypherCurrentCompiler.scala:323)
        at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:264)
        at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:219)
        at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubQuery$1(ExecutionEngine.scala:190)
        at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:195)
        at org.neo4j.cypher.internal.ExecutionEngine.executeSubQuery(ExecutionEngine.scala:188)
        at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:139)
        at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:121)
        at org.neo4j.bolt.dbapi.impl.BoltQueryExecutorImpl.executeQuery(BoltQueryExecutorImpl.java:52)
        at org.neo4j.bolt.runtime.statemachine.impl.AbstractTransactionStateMachineSPI$AbstractBoltResultHandle.start(AbstractTransactionStateMachineSPI.java:132)
        ... 21 more
Caused by: org.neo4j.exceptions.UnspecifiedKernelException: Newly created token should be unique.
        at org.neo4j.token.DelegatingTokenHolder.createToken(DelegatingTokenHolder.java:77)
        at org.neo4j.token.AbstractTokenHolderBase.innerGetOrCreateId(AbstractTokenHolderBase.java:70)
        at org.neo4j.token.AbstractTokenHolderBase.getOrCreateId(AbstractTokenHolderBase.java:58)
        at org.neo4j.kernel.impl.newapi.KernelToken.getOrCreateForName(KernelToken.java:258)
        at org.neo4j.kernel.impl.newapi.KernelToken.propertyKeyGetOrCreateForName(KernelToken.java:105)
        at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.getOrCreatePropertyKeyId(TransactionBoundQueryContext.scala:666)
        at org.neo4j.cypher.internal.planning.ExceptionTranslatingQueryContext.$anonfun$getOrCreatePropertyKeyId$1(ExceptionTranslatingQueryContext.scala:95)
        at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12)
        at org.neo4j.cypher.internal.planning.ExceptionTranslationSupport.translateException(ExceptionTranslationSupport.scala:33)
        ... 50 more
Caused by: org.neo4j.token.api.NonUniqueTokenException: The PropertyKey NamedToken[name:size, id:133, internal:false] is not unique, it existed as NamedToken[name:__org.neo4j.SchemaRule.IndexConfig.spatial.wgs-84.max, id:133, internal:true].
        at org.neo4j.token.TokenRegistry.put(TokenRegistry.java:73)
        at org.neo4j.token.DelegatingTokenHolder.createToken(DelegatingTokenHolder.java:73)
        ... 58 more
```

After restarting the server а database is not available:
```
020-03-04 10:36:44.873+0000 WARN [o.n.k.d.Database] [neo4j] Exception occurred while starting the database. Trying to stop already started components. Component 'org.neo4j.internal.recordstorage.RecordStorageEngine$2@5eeb7b5b' failed to initialize. Please see the attached cause exception "The PropertyKey NamedToken[name:size, id:134, internal:false] is not unique, it existed as null.".
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.internal.recordstorage.RecordStorageEngine$2@5eeb7b5b' failed to initialize. Please see the attached cause exception "The PropertyKey NamedToken[name:size, id:134, internal:false] is not unique, it existed as null.".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:426)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102)
        at org.neo4j.kernel.database.Database.start(Database.java:462)
        at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:187)
        at org.neo4j.dbms.database.DefaultDatabaseManager.startDatabase(DefaultDatabaseManager.java:132)
        at org.neo4j.dbms.database.DefaultDatabaseManager.initialiseDefaultDatabase(DefaultDatabaseManager.java:64)
        at org.neo4j.dbms.database.DefaultDatabaseInitializer.start0(DefaultDatabaseInitializer.java:39)
        at org.neo4j.kernel.lifecycle.SafeLifecycle.transition(SafeLifecycle.java:124)
        at org.neo4j.kernel.lifecycle.SafeLifecycle.start(SafeLifecycle.java:138)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:158)
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:145)
        at org.neo4j.server.database.CommunityGraphFactory.newDatabaseManagementService(CommunityGraphFactory.java:36)
        at org.neo4j.server.database.LifecycleManagingDatabaseService.start(LifecycleManagingDatabaseService.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:157)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:114)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:89)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
Caused by: org.neo4j.token.api.NonUniqueTokenException: The PropertyKey NamedToken[name:size, id:134, internal:false] is not unique, it existed as null.
        at org.neo4j.token.TokenRegistry.checkNameUniqueness(TokenRegistry.java:199)
        at org.neo4j.token.TokenRegistry.insertAllChecked(TokenRegistry.java:174)
        at org.neo4j.token.TokenRegistry.setInitialTokens(TokenRegistry.java:64)
        at org.neo4j.token.AbstractTokenHolderBase.setInitialTokens(AbstractTokenHolderBase.java:46)
        at org.neo4j.token.TokenHolders.setInitialTokens(TokenHolders.java:59)
        at org.neo4j.internal.recordstorage.RecordStorageEngine$2.init(RecordStorageEngine.java:458)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:405)
        ... 21 more
2020-03-04 10:36:44.875+0000 ERROR [o.n.d.d.DefaultDatabaseManager] Failed to start database: neo4j An error occurred! Unable to start database with name `neo4j`.
org.neo4j.dbms.api.DatabaseManagementException: An error occurred! Unable to start database with name `neo4j`.
        at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:191)
        at org.neo4j.dbms.database.DefaultDatabaseManager.startDatabase(DefaultDatabaseManager.java:132)
        at org.neo4j.dbms.database.DefaultDatabaseManager.initialiseDefaultDatabase(DefaultDatabaseManager.java:64)
        at org.neo4j.dbms.database.DefaultDatabaseInitializer.start0(DefaultDatabaseInitializer.java:39)
        at org.neo4j.kernel.lifecycle.SafeLifecycle.transition(SafeLifecycle.java:124)
        at org.neo4j.kernel.lifecycle.SafeLifecycle.start(SafeLifecycle.java:138)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:158)
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:145)
        at org.neo4j.server.database.CommunityGraphFactory.newDatabaseManagementService(CommunityGraphFactory.java:36)
        at org.neo4j.server.database.LifecycleManagingDatabaseService.start(LifecycleManagingDatabaseService.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:157)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:114)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:89)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
Caused by: java.lang.RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.internal.recordstorage.RecordStorageEngine$2@5eeb7b5b' failed to initialize. Please see the attached cause exception "The PropertyKey NamedToken[name:size, id:134, internal:false] is not unique, it existed as null.".
        at org.neo4j.kernel.database.Database.start(Database.java:478)
        at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:187)
        ... 17 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.internal.recordstorage.RecordStorageEngine$2@5eeb7b5b' failed to initialize. Please see the attached cause exception "The PropertyKey NamedToken[name:size, id:134, internal:false] is not unique, it existed as null.".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:426)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102)
        at org.neo4j.kernel.database.Database.start(Database.java:462)
        ... 18 more
Caused by: org.neo4j.token.api.NonUniqueTokenException: The PropertyKey NamedToken[name:size, id:134, internal:false] is not unique, it existed as null.
        at org.neo4j.token.TokenRegistry.checkNameUniqueness(TokenRegistry.java:199)
        at org.neo4j.token.TokenRegistry.insertAllChecked(TokenRegistry.java:174)
        at org.neo4j.token.TokenRegistry.setInitialTokens(TokenRegistry.java:64)
        at org.neo4j.token.AbstractTokenHolderBase.setInitialTokens(AbstractTokenHolderBase.java:46)
        at org.neo4j.token.TokenHolders.setInitialTokens(TokenHolders.java:59)
        at org.neo4j.internal.recordstorage.RecordStorageEngine$2.init(RecordStorageEngine.java:458)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:405)
        ... 21 more
```

**Comment by chrisvest** [comment]
@victorenator Can you share the entire debug.log, and describe the history of the store, like what versions have you been running and upgraded through?

**Comment by chrisvest** [comment]
@victorenator Also, can you confirm that the store has never been in a cluster? Neither Causal Cluster nor HA? It would be helpful if we can exclude those areas from the bug-hunt.

**Comment by victorenator** [comment]
> @victorenator Also, can you confirm that the store has never been in a cluster? Neither Causal Cluster nor HA? It would be helpful if we can exclude those areas from the bug-hunt.

Yes, only a single instance.

**Comment by chrisvest** [comment]
@victorenator Can you share the entire debug.log, and describe the history of the store, like what versions have you been running and upgraded through?

**Comment by victorenator** [comment]
> @victorenator Can you share the entire debug.log, and describe the history of the store, like what versions have you been running and upgraded through?

23 Jan I update the database from 3.5.14 to 4.0.0, and on Feb 28 — to 4.0.1.

[debug.log.gz](https://github.com/neo4j/neo4j/files/4289590/debug.log.gz)
Log contains:
- starting a server
- running the statement with error
- restarting a server with error

**Comment by chrisdostert** [comment]
@chrisvest just to make sure this isn't missed; for me the issue ONLY occurs with causal clustering enabled. I have been unable to reproduce it with single instance mode.

**Comment by jlarteaga** [comment]
I'm dealing with the same problem as @victorenator. I updated the database from 3.5 to 4.0.1 one month ago and it worked in production without any issues until a new backend version forced some changes in the structure of the nodes.

The flow is the same as described before: Trying to perform an insertion query causes:
```
The PropertyKey NamedToken[name:createdBy, id:59, internal:false] is not unique, it existed as NamedToken[name:__org.neo4j.SchemaRule.IndexConfig.spatial.cartesian-3d.min, id:59, internal:true].
```

The second time the query is executed, it causes no problem at all, but on a server restart, the database won't be available.

This happens on the community edition. No cluster configuration was used at all.

**Comment by jboler** [comment]
I'm seeing the same issue. Once on my local development instance that had a freshly created neo4j v4.0.1 DB:
```
2020-03-10 22:36:00.016+0000 INFO [c.n.k.i.p.PageCacheWarmer] [system] Page cache warmup completed. 127 pages loaded. Duration: 1s 68ms.
2020-03-10 22:36:00.217+0000 WARN [o.n.k.d.Database] [graph.db] Exception occurred while starting the database. Trying to stop already started components. Component 'org.neo4j.internal.recordstorage.RecordStorageEngine$2@17d26e65' failed to initialize. Please see the attached cause exception "The PropertyKey NamedToken[name:new_hire, id:78, internal:false] is not unique, it existed as null.".
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.internal.recordstorage.RecordStorageEngine$2@17d26e65' failed to initialize. Please see the attached cause exception "The PropertyKey NamedToken[name:new_hire, id:78, internal:false] is not unique, it existed as null.".
```
And then again on our application's staging environment backup run after upgrading the store from 3.5.14 to 4.0.1:
```
Execution of backup failed. The PropertyKey NamedToken[name:r_Custom2, id:176, internal:false] is not unique, it existed as null.
```

**Comment by chrisvest** [comment]
@jboler Can you attach the complete debug.log for the database that was created afresh? It's helpful that we are able to narrow down where the bug can hide.

**Comment by chrisvest** [comment]
The problem has been identified and will be fixed in an upcoming version. A mitigation strategy appears to be to move/rename/neutralise the `neostore.propertystore.db.index.id` file immediately after upgrading from 3.5 to 4.0.0, 4.0.1, or 4.0.2.

**Comment by chrisvest** [comment]
For those who have already upgraded, you can mitigate using the `neo4j-admin copy` command from the Enterprise Edition. Use that command to copy the database to a new location. The command will actually crash at the end, trying to print the schema information, but this is fine; the database is copied allright, but all the schema information will be gone, so you have to recreate all indexes and constraints. If you are on Community Edition, then download Neo4j Desktop. It includes a developer license for EE. (Disclaimer: I'm no lawyer, so you'll have to look into the licensing yourselves to verify if things are AOK on that, if that's a concern)

**Comment by jboler** [comment]
@chrisvest Thanks for the fix! Do I have to stop neo4j then delete or delete without stopping?

**Comment by chrisvest** [comment]
First stop, then remove the file.

**Comment by jlarteaga** [comment]
@chrisvest Thank you so much!

**Comment by chrisvest** [comment]
Furthermore, the upcoming fix in 4.0.3 will include runtime checks that prevent the "non unique token" exception from happening even if the store was migrated from 3.5 by a 4.0.0, 4.0.1, or 4.0.2 version of Neo4j. This means the mitigations mentioned above will no longer be necessary for databases that haven't observed that exception yet.

If the "non unique token" _has_ occurred, however, then a 4.0.3 upgrade alone cannot fix it. Only `neo4j-admin copy`, or a restore from a backup taken prior to the "non unique token" exception, can recover the database at that point.

**Comment by chrisvest** [comment]
Fix has been merged and will be released soon.

**Comment by malikalimoekhamedov** [comment]
Awesome!

**Comment by gpierrick** [comment]
Was this fixed? We're still experiencing this issue in Neo4j 4.0.7 @chrisvest

**Comment by chrisvest** [comment]
@gpierrick yes it's fixed. Look at the error you're seeing in detail to make sure it's the same. If it is, try the mitigations above. Otherwise open a new issue.

**Comment by gpierrick** [comment]
@chrisvest we're still getting it in a staging environment using 4.0.7

```
at org.neo4j.internal.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:302)
        at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
        at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
        at com.neo4j.causalclustering.core.state.machines.StateMachineCommitHelper.commit(StateMachineCommitHelper.java:56)
        at com.neo4j.causalclustering.core.state.machines.StateMachineCommitHelper.commit(StateMachineCommitHelper.java:51)
        at com.neo4j.causalclustering.core.state.machines.token.ReplicatedTokenStateMachine.applyToStore(ReplicatedTokenStateMachine.java:9
2)
        at com.neo4j.causalclustering.core.state.machines.token.ReplicatedTokenStateMachine.applyCommand(ReplicatedTokenStateMachine.java:7
4)
        at com.neo4j.causalclustering.core.state.machines.CoreStateMachines$StateMachineCommandDispatcher.dispatch(CoreStateMachines.java:1
19)
        at com.neo4j.causalclustering.core.state.machines.token.ReplicatedTokenRequest.dispatch(ReplicatedTokenRequest.java:94)
        at com.neo4j.causalclustering.core.state.CommandApplicationProcess.handleOperations(CommandApplicationProcess.java:252)
        at com.neo4j.causalclustering.core.state.CommandApplicationProcess.applyBatch(CommandApplicationProcess.java:228)
        at com.neo4j.causalclustering.core.state.CommandBatcher.flush(CommandBatcher.java:44)
        at com.neo4j.causalclustering.core.state.CommandApplicationProcess.applyUpTo(CommandApplicationProcess.java:192)
        at com.neo4j.causalclustering.core.state.CommandApplicationProcess.applyJob(CommandApplicationProcess.java:156)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.neo4j.token.api.NonUniqueTokenException: The PropertyKey NamedToken[name:teamId, id:148, internal:false] is not unique, it e
xisted as NamedToken[name:__org.neo4j.SchemaRule.IndexConfig.spatial.wgs-84.max, id:148, internal:true].
        at org.neo4j.token.TokenRegistry.put(TokenRegistry.java:73)
        at org.neo4j.token.AbstractTokenHolderBase.addToken(AbstractTokenHolderBase.java:52)
        at org.neo4j.internal.recordstorage.BridgingCacheAccess.addPropertyKeyToken(BridgingCacheAccess.java:68)
        at org.neo4j.internal.recordstorage.CacheInvalidationTransactionApplier.visitPropertyKeyTokenCommand(CacheInvalidationTransactionAp
plier.java:69)
```

**Comment by gpierrick** [comment]
Does that fix it? https://neo4j.com/developer/kb/explanation-of-error-db-fails-to-start-with-caused-by-org-neo4j-token-api-nonuniqueyokenexception-the-propertykey-namedtoken/

We're about to try this
