### ISSUE TITLE
Inconsistent library versions reminder.

### ISSUE THREAD

**Issue by kaifeng-h** [neo4j/neo4j#12413]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 2 inconsistent libraries and 2 false consistent libraries.

Take org.apache.commons:commons-lang3 for example, this library is declared as version 3.8 in community/cypher/runtime-util, 3.7 in community/cypher/front-end/frontend and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take org.apache.commons:commons-lang3 for example, if we harmonize all the library versions into 3.9. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table is listed below. It shows the overall harmonization effort by modules. The columns represents the number of library APIs and API calls(NA,NAC), deleted APIs and API calls(NDA,NDAC) as well as modified API and API calls(NMA,NMAC). Modified APIs refers to those APIs whose call graph is not the same as previous version. Take the first row for example, if upgrading the library into version 3.9. Given that 4 APIs is used in module community/kernel-api, 0 of them is deleted in a recommended version(which will throw a NoMethodFoundError unless re-compiling the project),  1 of them is regarded as modified which could break the former API contract.

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|community/kernel-api|4(4)|0(0)|1(1)|
|2|community/io|2(2)|0(0)|0(0)|
|3|community/cypher/runtime-util|0(0)|0(0)|0(0)|
|4|..|..|..|..|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. The table is listed below. 

|Module|File|Type|API|
|-|-|-|-|
|community/kernel-api|community/kernel-api/src/main/java/org/neo4j/internal/kernel/api/IndexQuery.java|modify|org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(java.lang.Object,java.lang.Object,java.lang.String[])|

As for false consistency, take org.scala-lang scala-library jar for example. The library is declared in version 2.11.12 in all modules. However they are declared differently.  As components are developed in parallel, if one single library version is updated, which could become inconsistent as mentioned above, may cause above-mentioned inconsistency issues

If you are interested, you can have a more complete and detailed report in the attached PDF file.
[neo4j neo4j.pdf](https://github.com/neo4j/neo4j/files/4271806/neo4j.neo4j.pdf)

**Comment by sherfert** [comment]
Thanks. We'll have a look into this!

**Comment by asashour** [comment]
I quickly looked into branch `4.1`, and I guess it is already fixed.

**Comment by sherfert** [comment]
@asashour it is partially fixed, and I have a PR under review to fix the remainder
