### ISSUE TITLE
[neo4j 4.0.7] Failed to do consistency check on the backup

### ISSUE THREAD

**Issue by alexlitvinenko** [neo4j/neo4j#12615]
- Neo4j version: 4.0.7
- Operating system: Docker neo4j:4.0.7-enterprise
- APOC: 4.0.0.17

- **Steps to reproduce**
I'm trying to do hot backup with the following command: `neo4j-admin backup`
It works but after several backups I'm getting:  `Failed to do consistency check on the backup`
```
Index structure consistency check
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Full Consistency Check
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
...................Failed to do consistency check on the backup
```

Then I ran the following command: `neo4j-admin check-consistency --verbose --backup /data/graph.db`
```
org.neo4j.cli.CommandFailedException: Consistency checking failed.Full consistency check did not complete
	at org.neo4j.consistency.CheckConsistencyCommand.execute(CheckConsistencyCommand.java:161)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:59)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1743)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:77)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:58)
Caused by: org.neo4j.consistency.checking.full.ConsistencyCheckIncompleteException: Full consistency check did not complete
	at org.neo4j.consistency.checking.full.FullCheck.execute(FullCheck.java:186)
	at org.neo4j.consistency.checking.full.FullCheck.execute(FullCheck.java:102)
	at org.neo4j.consistency.ConsistencyCheckService.runFullConsistencyCheck(ConsistencyCheckService.java:257)
	at org.neo4j.consistency.ConsistencyCheckService.runFullConsistencyCheck(ConsistencyCheckService.java:158)
	at org.neo4j.consistency.CheckConsistencyCommand.execute(CheckConsistencyCommand.java:139)
	... 10 more
Caused by: org.neo4j.consistency.checking.full.ConsistencyCheckIncompleteException: Full consistency check did not complete
	at org.neo4j.consistency.checking.full.TaskExecutor.execute(TaskExecutor.java:43)
	at org.neo4j.consistency.checking.full.FullCheck.execute(FullCheck.java:170)
	... 14 more
Caused by: java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$UnmodifiableList.remove(Collections.java:1318)
	at org.neo4j.kernel.api.impl.index.LucenePartitionAllDocumentsReader$2.match(LucenePartitionAllDocumentsReader.java:124)
	at org.apache.lucene.search.FilteredDocIdSetIterator.nextDoc(FilteredDocIdSetIterator.java:64)
	at org.neo4j.kernel.api.impl.index.LucenePartitionAllDocumentsReader$1.fetchNextOrNull(LucenePartitionAllDocumentsReader.java:72)
	at org.neo4j.kernel.api.impl.index.LucenePartitionAllDocumentsReader$1.fetchNextOrNull(LucenePartitionAllDocumentsReader.java:64)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
	at org.neo4j.internal.helpers.collection.CombiningIterator.fetchNextOrNull(CombiningIterator.java:52)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
	at org.neo4j.kernel.api.impl.schema.reader.LuceneAllEntriesIndexAccessorReader$1.fetchNextOrNull(LuceneAllEntriesIndexAccessorReader.java:63)
	at org.neo4j.kernel.api.impl.schema.reader.LuceneAllEntriesIndexAccessorReader$1.fetchNextOrNull(LuceneAllEntriesIndexAccessorReader.java:57)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
	at org.neo4j.consistency.checking.full.SequentialRecordScanner.scan(SequentialRecordScanner.java:38)
	at org.neo4j.consistency.checking.full.RecordScanner.run(RecordScanner.java:61)
	at org.neo4j.consistency.checking.full.SequentialRecordScanner.run(SequentialRecordScanner.java:26)
	at org.neo4j.consistency.checking.full.TaskExecutor.execute(TaskExecutor.java:38)
	... 15 more
```

I can workaround the issue by dropping all fulltext indices and creating them again. But as I said it fails again after several backups.

**Comment by tinwelint** [comment]
Hi, this is an issue that has been fixed in the upcoming 4.2 version. I will backport this to 4.0 and 4.1 so that it will end up in e.g. 4.0.9

**Comment by alexlitvinenko** [comment]
Cool! I'm  looking forward when it appears in 4.0.x.

**Comment by alexlitvinenko** [comment]
I've upgraded my neo4j to 4.0.9.
Full consistency check still fails but with new error:
```
org.neo4j.cli.CommandFailedException: Consistency checking failed.Full consistency check did not complete
	at org.neo4j.consistency.CheckConsistencyCommand.execute(CheckConsistencyCommand.java:161)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:59)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1743)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:87)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:65)
Caused by: org.neo4j.consistency.checking.full.ConsistencyCheckIncompleteException: Full consistency check did not complete
	at org.neo4j.consistency.checking.full.FullCheck.execute(FullCheck.java:190)
	at org.neo4j.consistency.checking.full.FullCheck.execute(FullCheck.java:104)
	at org.neo4j.consistency.ConsistencyCheckService.runFullConsistencyCheck(ConsistencyCheckService.java:257)
	at org.neo4j.consistency.ConsistencyCheckService.runFullConsistencyCheck(ConsistencyCheckService.java:158)
	at org.neo4j.consistency.CheckConsistencyCommand.execute(CheckConsistencyCommand.java:139)
	... 10 more
Caused by: org.neo4j.consistency.checking.full.ConsistencyCheckIncompleteException: Full consistency check did not complete
	at org.neo4j.consistency.checking.full.TaskExecutor.execute(TaskExecutor.java:43)
	at org.neo4j.consistency.checking.full.FullCheck.execute(FullCheck.java:174)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 690 out of bounds for length 42
	at org.apache.lucene.util.FixedBits.get(FixedBits.java:39)
	at org.neo4j.kernel.api.impl.index.LucenePartitionAllDocumentsReader$2.match(LucenePartitionAllDocumentsReader.java:129)
	at org.apache.lucene.search.FilteredDocIdSetIterator.nextDoc(FilteredDocIdSetIterator.java:64)
	at org.neo4j.kernel.api.impl.index.LucenePartitionAllDocumentsReader$1.fetchNextOrNull(LucenePartitionAllDocumentsReader.java:71)
	at org.neo4j.kernel.api.impl.index.LucenePartitionAllDocumentsReader$1.fetchNextOrNull(LucenePartitionAllDocumentsReader.java:63)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
	at org.neo4j.internal.helpers.collection.CombiningIterator.fetchNextOrNull(CombiningIterator.java:48)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
	at org.neo4j.kernel.api.impl.schema.reader.LuceneAllEntriesIndexAccessorReader$1.fetchNextOrNull(LuceneAllEntriesIndexAccessorReader.java:63)
	at org.neo4j.kernel.api.impl.schema.reader.LuceneAllEntriesIndexAccessorReader$1.fetchNextOrNull(LuceneAllEntriesIndexAccessorReader.java:57)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
	at org.neo4j.consistency.checking.full.SequentialRecordScanner.scan(SequentialRecordScanner.java:38)
	at org.neo4j.consistency.checking.full.RecordScanner.run(RecordScanner.java:61)
	at org.neo4j.consistency.checking.full.SequentialRecordScanner.run(SequentialRecordScanner.java:26)
	at org.neo4j.consistency.checking.full.TaskExecutor.execute(TaskExecutor.java:38)
	... 15 more

```

**Comment by tinwelint** [comment]
Yet another problem with iterating over all Lucene index documents in the consistency checker... I think this iterator approach should be rewritten. Let me get to the bottom of this.

**Comment by tinwelint** [comment]
Is it a large database and can you share it?

**Comment by alexlitvinenko** [comment]
The db backup is ~1GB. Unfortunately I cannot share it.

BTW, Does this problem exist in v4.2.x?

**Comment by tinwelint** [comment]
Yes, almost certainly. As a workaround you can turn off consistency check during backup just to get past this issue until it's fixed.

**Comment by tinwelint** [comment]
This has now been fixed and should be included in the next round of patch releases

**Comment by mnd999** [comment]
Closing as it seems like this was fixed some time ago
