### ISSUE TITLE
MATCH query throws InternalException

### ISSUE THREAD

**Issue by InverseIntegral** [neo4j/neo4j#12876]
The following query

```
MATCH (n:Person) WHERE ((n.a = n.a) OR n.b) XOR (n.b) RETURN n
```

throws an unexpected exception when executed by the Java driver:

```
Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: Expected 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n'], Predicates: ['n:Person', 'n.a = n.a OR n.b OR n.b', 'not n.a = n.a OR not n.b', 'not n.b']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n -> Variable(n)),QueryPagination(None,None),Selections(Set())),None,None) 


Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n'], Predicates: ['n:Person', 'not n.a = n.a', 'not n.a = n.a OR not n.b', 'n.a = n.a OR n.b OR n.b', 'not n.b']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n -> Variable(n)),QueryPagination(None,None),Selections(Set())),None,None)
Plan: ProduceResult(List(n)) {
  LHS -> Selection(Ands(Vector(Ors(List(Not(Equals(Property(Variable(n),PropertyKeyName(a)),Property(Variable(n),PropertyKeyName(a)))), Not(Property(Variable(n),PropertyKeyName(b))))), Ors(List(Equals(Property(Variable(n),PropertyKeyName(a)),Property(Variable(n),PropertyKeyName(a))), Property(Variable(n),PropertyKeyName(b)), Property(Variable(n),PropertyKeyName(b))))))) {
    LHS -> Distinct(Map(n -> Variable(n))) {
      LHS -> Union() {
        LHS -> Selection(Ands(Vector(Not(Property(Variable(n),PropertyKeyName(b))), Not(Equals(Property(Variable(n),PropertyKeyName(a)),Property(Variable(n),PropertyKeyName(a))))))) {
          LHS -> NodeByLabelScan(n, LabelName(Person), Set(), IndexOrderNone) {}
        }
        RHS -> Selection(Ands(Vector(Not(Property(Variable(n),PropertyKeyName(b)))))) {
          LHS -> NodeByLabelScan(n, LabelName(Person), Set(), IndexOrderNone) {}
        }
      }
    }
  }
} 


Differences:
 - QueryGraph
    A: QueryGraph {Nodes: ['n'], Predicates: ['n:Person', 'n.a = n.a OR n.b OR n.b', 'not n.a = n.a OR not n.b', 'not n.b']}
    B: QueryGraph {Nodes: ['n'], Predicates: ['n:Person', 'not n.a = n.a', 'not n.a = n.a OR not n.b', 'n.a = n.a OR n.b OR n.b', 'not n.b']}

	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:131)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:115)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:285)
	... 7 more
Caused by: org.neo4j.exceptions.InternalException: Expected 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n'], Predicates: ['n:Person', 'n.a = n.a OR n.b OR n.b', 'not n.a = n.a OR not n.b', 'not n.b']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n -> Variable(n)),QueryPagination(None,None),Selections(Set())),None,None) 


Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n'], Predicates: ['n:Person', 'not n.a = n.a', 'not n.a = n.a OR not n.b', 'n.a = n.a OR n.b OR n.b', 'not n.b']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n -> Variable(n)),QueryPagination(None,None),Selections(Set())),None,None)
Plan: ProduceResult(List(n)) {
  LHS -> Selection(Ands(Vector(Ors(List(Not(Equals(Property(Variable(n),PropertyKeyName(a)),Property(Variable(n),PropertyKeyName(a)))), Not(Property(Variable(n),PropertyKeyName(b))))), Ors(List(Equals(Property(Variable(n),PropertyKeyName(a)),Property(Variable(n),PropertyKeyName(a))), Property(Variable(n),PropertyKeyName(b)), Property(Variable(n),PropertyKeyName(b))))))) {
    LHS -> Distinct(Map(n -> Variable(n))) {
      LHS -> Union() {
        LHS -> Selection(Ands(Vector(Not(Property(Variable(n),PropertyKeyName(b))), Not(Equals(Property(Variable(n),PropertyKeyName(a)),Property(Variable(n),PropertyKeyName(a))))))) {
          LHS -> NodeByLabelScan(n, LabelName(Person), Set(), IndexOrderNone) {}
        }
        RHS -> Selection(Ands(Vector(Not(Property(Variable(n),PropertyKeyName(b)))))) {
          LHS -> NodeByLabelScan(n, LabelName(Person), Set(), IndexOrderNone) {}
        }
      }
    }
  }
} 


Differences:
 - QueryGraph
    A: QueryGraph {Nodes: ['n'], Predicates: ['n:Person', 'n.a = n.a OR n.b OR n.b', 'not n.a = n.a OR not n.b', 'not n.b']}
    B: QueryGraph {Nodes: ['n'], Predicates: ['n:Person', 'not n.a = n.a', 'not n.a = n.a OR not n.b', 'n.a = n.a OR n.b OR n.b', 'not n.b']}

	at org.neo4j.cypher.internal.compiler.planner.logical.steps.VerifyBestPlan$.apply(VerifyBestPlan.scala:70)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.plan(QueryPlanner.scala:120)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.process(QueryPlanner.scala:63)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.process(QueryPlanner.scala:51)
	at org.neo4j.cypher.internal.frontend.phases.Phase.$anonfun$transform$1(Phase.scala:35)
	at org.neo4j.cypher.internal.frontend.helpers.package$.$anonfun$closing$1(package.scala:24)
	at org.neo4j.cypher.internal.frontend.helpers.package$.using(package.scala:32)
	at org.neo4j.cypher.internal.frontend.helpers.package$.closing(package.scala:24)
	at org.neo4j.cypher.internal.frontend.phases.Phase.transform(Phase.scala:34)
	at org.neo4j.cypher.internal.frontend.phases.Phase.transform$(Phase.scala:33)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.transform(QueryPlanner.scala:51)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:79)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.If.transform(Transformer.scala:96)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:79)
	at org.neo4j.cypher.internal.compiler.CypherPlanner.planPreparedQuery(CypherPlanner.scala:69)
	at org.neo4j.cypher.internal.planning.CypherPlanner.doCreatePlan(CypherPlanner.scala:399)
	at org.neo4j.cypher.internal.planning.CypherPlanner.org$neo4j$cypher$internal$planning$CypherPlanner$$createPlan$1(CypherPlanner.scala:347)
	at org.neo4j.cypher.internal.planning.CypherPlanner$$anon$1.compile(CypherPlanner.scala:356)
	at org.neo4j.cypher.internal.planning.CypherPlanner$$anon$1.compile(CypherPlanner.scala:355)
	at org.neo4j.cypher.internal.QueryCache.$anonfun$compileAndCache$1(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.compileOrCompileWithExpressionCodeGenAndCache(QueryCache.scala:304)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:193)
	at org.neo4j.cypher.internal.planning.CypherPlanner.doPlan(CypherPlanner.scala:374)
	at org.neo4j.cypher.internal.planning.CypherPlanner.parseAndPlan(CypherPlanner.scala:265)
	at org.neo4j.cypher.internal.CypherCurrentCompiler.compile(CypherCurrentCompiler.scala:152)
	at org.neo4j.cypher.internal.MasterCompiler.compile(MasterCompiler.scala:86)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$compilerWithExpressionCodeGenOption$2(ExecutionEngine.scala:229)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$2.compile(ExecutionEngine.scala:237)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$2.compile(ExecutionEngine.scala:231)
	at org.neo4j.cypher.internal.QueryCache.$anonfun$compileAndCache$1(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.compileOrCompileWithExpressionCodeGenAndCache(QueryCache.scala:304)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:193)
	at org.neo4j.cypher.internal.ExecutionEngine.getOrCompile(ExecutionEngine.scala:287)
	at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:200)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubquery$1(ExecutionEngine.scala:178)
	at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:183)
	at org.neo4j.cypher.internal.ExecutionEngine.executeSubquery(ExecutionEngine.scala:175)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:125)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:127)
	... 9 more

```

**Neo4j Version:** 4.4.5
**Operating System:** 5.16.16 Arch
**API:** Java

### Expected behavior
I would expect the query to not throw any exception.

### Actual behavior
An exception is thrown.

**Comment by HannesSandberg** [comment]
Thank you for the report! We will look into this.

**Comment by arnefischereit** [comment]
Hi @InverseIntegral,

This is a known issue and [fixed in 4.4.6](https://neo4j.com/release-notes/database/neo4j-4-4-6/).

> Fixed an error due to which very particular queries with the same predicate on both sides of an OR expression could not be planned.

Please let us know if that should not solve your problem.

Cheers,

Arne

**Comment by InverseIntegral** [comment]
Thank you for the fast reply @arnefischereit. The problem seems to be resolved :+1:

**Comment by InverseIntegral** [comment]
I did some more testing and the following query:

```
MATCH (n:L) WHERE (n.a AND (NOT ((n.a OR n.a) AND false))) XOR n.a RETURN n
```

Seems to still throw an exception in the newest version (4.4.6):

```
Caused by: org.neo4j.graphdb.QueryExecutionException: Expected 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'n.a']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n -> Variable(n)),QueryPagination(None,None),Selections(Set())),None,None) 


Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'not n.a', 'n.a']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n -> Variable(n)),QueryPagination(None,None),Selections(Set())),None,None)
Plan: ProduceResult(List(n)) {
  LHS -> Selection(Ands(Vector(Ors(List(Not(Property(Variable(n),PropertyKeyName(a))), Not(Property(Variable(n),PropertyKeyName(a))))), Ors(List(Not(Property(Variable(n),PropertyKeyName(a))), Property(Variable(n),PropertyKeyName(a)), Not(Property(Variable(n),PropertyKeyName(a))))), Ors(List(Not(Property(Variable(n),PropertyKeyName(a))), Not(False()), Property(Variable(n),PropertyKeyName(a))))))) {
    LHS -> Distinct(Map(n -> Variable(n))) {
      LHS -> Union() {
        LHS -> Selection(Ands(Vector(Not(Property(Variable(n),PropertyKeyName(a))), CoerceToPredicate(Property(Variable(n),PropertyKeyName(a)))))) {
          LHS -> NodeByLabelScan(n, LabelName(L), Set(), IndexOrderNone) {}
        }
        RHS -> Selection(Ands(Vector(Not(Property(Variable(n),PropertyKeyName(a))), CoerceToPredicate(Property(Variable(n),PropertyKeyName(a)))))) {
          LHS -> NodeByLabelScan(n, LabelName(L), Set(), IndexOrderNone) {}
        }
      }
    }
  }
} 


Differences:
 - QueryGraph
    A: QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'n.a']}
    B: QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'not n.a', 'n.a']}

	at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:293)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:274)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:268)
	at ch.ethz.ast.gdblancer.neo4j.Neo4JConnection.execute(Neo4JConnection.java:42)
	at ch.ethz.ast.gdblancer.neo4j.Neo4JQuery.execute(Neo4JQuery.java:34)
	... 3 more
Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: Expected 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'n.a']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n -> Variable(n)),QueryPagination(None,None),Selections(Set())),None,None) 


Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'not n.a', 'n.a']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n -> Variable(n)),QueryPagination(None,None),Selections(Set())),None,None)
Plan: ProduceResult(List(n)) {
  LHS -> Selection(Ands(Vector(Ors(List(Not(Property(Variable(n),PropertyKeyName(a))), Not(Property(Variable(n),PropertyKeyName(a))))), Ors(List(Not(Property(Variable(n),PropertyKeyName(a))), Property(Variable(n),PropertyKeyName(a)), Not(Property(Variable(n),PropertyKeyName(a))))), Ors(List(Not(Property(Variable(n),PropertyKeyName(a))), Not(False()), Property(Variable(n),PropertyKeyName(a))))))) {
    LHS -> Distinct(Map(n -> Variable(n))) {
      LHS -> Union() {
        LHS -> Selection(Ands(Vector(Not(Property(Variable(n),PropertyKeyName(a))), CoerceToPredicate(Property(Variable(n),PropertyKeyName(a)))))) {
          LHS -> NodeByLabelScan(n, LabelName(L), Set(), IndexOrderNone) {}
        }
        RHS -> Selection(Ands(Vector(Not(Property(Variable(n),PropertyKeyName(a))), CoerceToPredicate(Property(Variable(n),PropertyKeyName(a)))))) {
          LHS -> NodeByLabelScan(n, LabelName(L), Set(), IndexOrderNone) {}
        }
      }
    }
  }
} 


Differences:
 - QueryGraph
    A: QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'n.a']}
    B: QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'not n.a', 'n.a']}

	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:131)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:115)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:285)
	... 7 more
Caused by: org.neo4j.exceptions.InternalException: Expected 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'n.a']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n -> Variable(n)),QueryPagination(None,None),Selections(Set())),None,None) 


Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'not n.a', 'n.a']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n -> Variable(n)),QueryPagination(None,None),Selections(Set())),None,None)
Plan: ProduceResult(List(n)) {
  LHS -> Selection(Ands(Vector(Ors(List(Not(Property(Variable(n),PropertyKeyName(a))), Not(Property(Variable(n),PropertyKeyName(a))))), Ors(List(Not(Property(Variable(n),PropertyKeyName(a))), Property(Variable(n),PropertyKeyName(a)), Not(Property(Variable(n),PropertyKeyName(a))))), Ors(List(Not(Property(Variable(n),PropertyKeyName(a))), Not(False()), Property(Variable(n),PropertyKeyName(a))))))) {
    LHS -> Distinct(Map(n -> Variable(n))) {
      LHS -> Union() {
        LHS -> Selection(Ands(Vector(Not(Property(Variable(n),PropertyKeyName(a))), CoerceToPredicate(Property(Variable(n),PropertyKeyName(a)))))) {
          LHS -> NodeByLabelScan(n, LabelName(L), Set(), IndexOrderNone) {}
        }
        RHS -> Selection(Ands(Vector(Not(Property(Variable(n),PropertyKeyName(a))), CoerceToPredicate(Property(Variable(n),PropertyKeyName(a)))))) {
          LHS -> NodeByLabelScan(n, LabelName(L), Set(), IndexOrderNone) {}
        }
      }
    }
  }
} 


Differences:
 - QueryGraph
    A: QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'n.a']}
    B: QueryGraph {Nodes: ['n'], Predicates: ['not n.a OR not false OR n.a', 'not n.a OR not n.a', 'n:L', 'not n.a OR n.a OR not n.a', 'not n.a', 'n.a']}

	at org.neo4j.cypher.internal.compiler.planner.logical.steps.VerifyBestPlan$.apply(VerifyBestPlan.scala:70)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.plan(QueryPlanner.scala:121)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.process(QueryPlanner.scala:63)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.process(QueryPlanner.scala:51)
	at org.neo4j.cypher.internal.frontend.phases.Phase.$anonfun$transform$1(Phase.scala:36)
	at org.neo4j.cypher.internal.frontend.helpers.package$.$anonfun$closing$1(package.scala:24)
	at org.neo4j.cypher.internal.frontend.helpers.package$.using(package.scala:32)
	at org.neo4j.cypher.internal.frontend.helpers.package$.closing(package.scala:24)
	at org.neo4j.cypher.internal.frontend.phases.Phase.transform(Phase.scala:35)
	at org.neo4j.cypher.internal.frontend.phases.Phase.transform$(Phase.scala:33)
	at org.neo4j.cypher.internal.compiler.planner.logical.QueryPlanner$.transform(QueryPlanner.scala:51)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:79)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:78)
	at org.neo4j.cypher.internal.frontend.phases.If.transform(Transformer.scala:96)
	at org.neo4j.cypher.internal.frontend.phases.PipeLine.transform(Transformer.scala:79)
	at org.neo4j.cypher.internal.compiler.CypherPlanner.planPreparedQuery(CypherPlanner.scala:70)
	at org.neo4j.cypher.internal.planning.CypherPlanner.doCreatePlan(CypherPlanner.scala:404)
	at org.neo4j.cypher.internal.planning.CypherPlanner.org$neo4j$cypher$internal$planning$CypherPlanner$$createPlan$1(CypherPlanner.scala:352)
	at org.neo4j.cypher.internal.planning.CypherPlanner$$anon$1.compile(CypherPlanner.scala:361)
	at org.neo4j.cypher.internal.planning.CypherPlanner$$anon$1.compile(CypherPlanner.scala:360)
	at org.neo4j.cypher.internal.QueryCache.$anonfun$compileAndCache$1(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.compileOrCompileWithExpressionCodeGenAndCache(QueryCache.scala:304)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:193)
	at org.neo4j.cypher.internal.planning.CypherPlanner.doPlan(CypherPlanner.scala:379)
	at org.neo4j.cypher.internal.planning.CypherPlanner.parseAndPlan(CypherPlanner.scala:269)
	at org.neo4j.cypher.internal.CypherCurrentCompiler.compile(CypherCurrentCompiler.scala:152)
	at org.neo4j.cypher.internal.MasterCompiler.compile(MasterCompiler.scala:86)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$compilerWithExpressionCodeGenOption$2(ExecutionEngine.scala:229)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$2.compile(ExecutionEngine.scala:237)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$2.compile(ExecutionEngine.scala:231)
	at org.neo4j.cypher.internal.QueryCache.$anonfun$compileAndCache$1(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.compileOrCompileWithExpressionCodeGenAndCache(QueryCache.scala:304)
	at org.neo4j.cypher.internal.QueryCache.compileAndCache(QueryCache.scala:276)
	at org.neo4j.cypher.internal.QueryCache.computeIfAbsentOrStale(QueryCache.scala:193)
	at org.neo4j.cypher.internal.ExecutionEngine.getOrCompile(ExecutionEngine.scala:287)
	at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:200)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubquery$1(ExecutionEngine.scala:178)
	at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:183)
	at org.neo4j.cypher.internal.ExecutionEngine.executeSubquery(ExecutionEngine.scala:175)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:125)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:127)
	... 9 more
```
Should I open a new issue so you can track this separately?

**Comment by arnefischereit** [comment]
Thank you for your thorough testing. I have opened a new issue #12877 and will continue investigation over there.
