### ISSUE TITLE
Another UnknownError about sorted plan

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13246]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
MATCH ()<-[r0]-() RETURN exists{RETURN DISTINCT (null = reduce(a=null,b in [null]|a+b)) ORDER BY r0.k};

error message:
Neo.DatabaseError.General.UnknownError
Expected a sorted plan but got
.distinct("NULL = reduce(a = NULL, b IN $`  AUTOLIST0` | a + b) AS `(null = reduce(a=null,b in [null]|a+b))`")
.argument("r0")
.build()

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by pontusmelke** [comment]
Thanks @ljhhuxiaoba 
Looks like the same issue but we'll make sure to look at both of them.

Best regards,
Pontus

**Comment by inmost-light** [comment]
Thank you for reporting, this has been fixed in 5.10.

**Comment by ljhhuxiaoba** [comment]
This bug is still in neo4j 5.12.0 community version(docker container).
error message:
Expected a sorted plan but got
.projection(project = Seq("NULL = reduce(a = NULL, b IN $`  AUTOLIST0` | a + b) AS `(null = reduce(a=null,b in [null]|a+b))`"), discard = Set("r0"))
.argument("r0")
.build()

**Comment by inmost-light** [comment]
@ljhhuxiaoba My bad, should be fixed in the upcoming __5.13__.
