### ISSUE TITLE
Webadmin doesn't works behind HTTPS

### ISSUE THREAD

**Issue by ayosec** [neo4j/neo4j#1488]
Webadmin interface doesn't use the `X-Forwarded-Host` and `X-Forwarded-Proto` headers to generate URLs. The URLs are correctly generated in the REST interface.

### With 1.9.4

A basic query

    $ curl -i -H 'X-Forwarded-Host: external.foo.bar:1234' -H 'X-Forwarded-Proto: https' localhost:7474/db/data/
    HTTP/1.1 200 OK
    Content-Length: 876
    Content-Type: application/json; charset=UTF-8
    Access-Control-Allow-Origin: *
    Server: Jetty(6.1.25)

    {
      "extensions" : {
        "CypherPlugin" : {
          "execute_query" : "https://external.foo.bar:1234/db/data/ext/CypherPlugin/graphdb/execute_query"
        },
        "GremlinPlugin" : {
          "execute_script" : "https://external.foo.bar:1234/db/data/ext/GremlinPlugin/graphdb/execute_script"
        }
      },
      "node" : "https://external.foo.bar:1234/db/data/node",
      "reference_node" : "https://external.foo.bar:1234/db/data/node/0",
      "node_index" : "https://external.foo.bar:1234/db/data/index/node",
      "relationship_index" : "https://external.foo.bar:1234/db/data/index/relationship",
      "extensions_info" : "https://external.foo.bar:1234/db/data/ext",
      "relationship_types" : "https://external.foo.bar:1234/db/data/relationship/types",
      "batch" : "https://external.foo.bar:1234/db/data/batch",
      "cypher" : "https://external.foo.bar:1234/db/data/cypher",
      "neo4j_version" : "1.9.4"
    }

A request simulating a browser

    $ curl -i -H 'Accept: text/html' -H 'X-Forwarded-Host: external.foo.bar:1234' -H 'X-Forwarded-Proto: https' localhost:7474/db/data/
    HTTP/1.1 200 OK
    Content-Length: 1195
    Content-Type: text/html; charset=UTF-8
    Access-Control-Allow-Origin: *
    Server: Jetty(6.1.25)

    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
    <html><head><title>Root</title><meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <link href='http://resthtml.neo4j.org/style/rest.css' rel='stylesheet' type='text/css'>
    <script type='text/javascript' src='/webadmin/htmlbrowse.js'></script>
    </head>
    <body onload='javascript:neo4jHtmlBrowse.start();' id='root'>
    <div id='content'><div id='header'><h1><a title='Neo4j REST interface' href='/'><span>Neo4j REST interface</span></a></h1></div>
    <div id='page-body'>
    <table class="root"><caption>Root</caption>
    <tr class='odd'><th>relationship_index</th><td><a href="https://external.foo.bar:1234/db/data/index/relationship">https://external.foo.bar:1234/db/data/index/relationship</a></td></tr>
    <tr><th>node_index</th><td><a href="https://external.foo.bar:1234/db/data/index/node">https://external.foo.bar:1234/db/data/index/node</a></td></tr>
    <tr class='odd'><th>reference_node</th><td><a href="https://external.foo.bar:1234/db/data/node/0" class="node">https://external.foo.bar:1234/db/data/node/0</a></td></tr>
    </table>
    <div class='break'>&nbsp;</div></div></div></body></html>

In both cases, the URLs are `https://external.foo.bar:1234/...`

However, if we try to get the webadmin interface:

    $ curl -i -H 'Accept: text/html' -H 'X-Forwarded-Host: external.foo.bar:1234' -H 'X-Forwarded-Proto: https' localhost:7474
    HTTP/1.1 303 See Other
    Location: http://localhost:7474/webadmin
    Content-Type: text/html
    Access-Control-Allow-Origin: *
    Content-Length: 0
    Server: Jetty(6.1.25)

    $ curl -i -H 'Accept: text/html' -H 'X-Forwarded-Host: external.foo.bar:1234' -H 'X-Forwarded-Proto: https' localhost:7474/webadmin
    HTTP/1.1 302 Found
    Location: http://localhost:7474/webadmin/
    Content-Length: 0
    Server: Jetty(6.1.25)

In both cases, the generated URL is `http://localhost:7474/`

### With 2.0.0-M06

The same behaviour is found in 2.0.0-M06

    $ curl -i -H 'Accept: text/html' -H 'X-Forwarded-Host: external.foo.bar:1234' -H 'X-Forwarded-Proto: https' localhost:7474/
    HTTP/1.1 303 See Other
    Location: http://localhost:7474/browser
    Content-Type: text/html
    Access-Control-Allow-Origin: *
    Content-Length: 0
    Server: Jetty(9.0.5.v20130815)

    $ curl -i -H 'Accept: text/html' -H 'X-Forwarded-Host: external.foo.bar:1234' -H 'X-Forwarded-Proto: https' localhost:7474/db/data/
    HTTP/1.1 200 OK
    Content-Type: text/html; charset=UTF-8
    Access-Control-Allow-Origin: *
    Content-Length: 1195
    Server: Jetty(9.0.5.v20130815)

    [...] <a href="https://external.foo.bar:1234/db/data/node/0" class="node">https://external.foo.bar:1234/db/data/node/0</a></td></tr>
    </table>

**Comment by albertoperdomo** [comment]
@cleishm Any plans to get this fixed? It's still broken in 2.1.x as well as 2.2.0-RC1.
Redirect from `/` to `/browser` is still dropping the SSL protocol. I know the issues in webadmin won't get fixed as 1.9 is legacy and I guess webadmin will be discontinued at some point, but it would be really nice if 2.1/2.2 would redirect correctly to the new browser.

Neo4j 2.1.7:
```
$ curl -s localhost:7474/db/data/ | jq .neo4j_version
"2.1.7"

$ curl -i -w \\n localhost:7474/ \
>     -H 'Host: db-X.graphenedb.com' \
>     -H 'X-Forwarded-Proto: https' \
>     -H 'Accept: text/html'
HTTP/1.1 303 See Other
Location: https://db-X.graphenedb.com/browser
Content-Type: text/html
Access-Control-Allow-Origin: *
Content-Length: 0
Server: Jetty(9.0.5.v20130815)

$ curl -i -w \\n localhost:7474/browser \
>     -H 'Host: db-X.graphenedb.com' \
>     -H 'X-Forwarded-Proto: https' \
>     -H 'Accept: text/html'
HTTP/1.1 302 Found
Location: http://db-X.graphenedb.com/browser/
Content-Length: 0
```

Neo4j 2.2.0-RC1:
```
$ curl -s localhost:7474/db/data/ | jq .neo4j_version
"2.2.0-RC01"

$ curl -i -w \\n localhost:7474/ \
>     -H 'Host: db-X.graphenedb.com' \
>     -H 'X-Forwarded-Proto: https' \
>     -H 'Accept: text/html'
HTTP/1.1 303 See Other
Date: Tue, 17 Mar 2015 16:33:41 GMT
Location: https://db-X.graphenedb.com/browser
Content-Type: text/html
Access-Control-Allow-Origin: *
Content-Length: 0
Server: Jetty(9.2.4.v20141103)

$ curl -i -w \\n localhost:7474/browser \
>     -H 'Host: db-X.graphenedb.com' \
>     -H 'X-Forwarded-Proto: https' \
>     -H 'Accept: text/html'
HTTP/1.1 302 Found
Date: Tue, 17 Mar 2015 16:34:16 GMT
Location: http://db-X.graphenedb.com/browser/
Content-Length: 0
Server: Jetty(9.2.4.v20141103)
```

**Comment by cleishm** [comment]
Resolved by #4244 and #4246

**Comment by albertoperdomo** [comment]
Hello @cleishm. It seems the fix is not working as expected. The behavior is still the same. The protocol is still dropped:

```
$ curl -s localhost:7474/db/data/ | jq .neo4j_version
"2.2.0"
$ curl -i -w \\n localhost:7474/ \
>       -H 'Host: db-X.graphenedb.com' \
>       -H 'X-Forwarded-Proto: https' \
>       -H 'Accept: text/html'
HTTP/1.1 303 See Other
Date: Thu, 26 Mar 2015 08:50:03 GMT
Location: https://db-X.graphenedb.com/browser/
Content-Type: text/html
Access-Control-Allow-Origin: *
Content-Length: 0
Server: Jetty(9.2.4.v20141103)

$ curl -i -w \\n localhost:7474/browser \
>       -H 'Host: db-X.graphenedb.com' \
>       -H 'X-Forwarded-Proto: https' \
>       -H 'Accept: text/html'
HTTP/1.1 302 Found
Date: Thu, 26 Mar 2015 08:50:44 GMT
Location: http://db-X.graphenedb.com/browser/
Content-Length: 0
Server: Jetty(9.2.4.v20141103)
```

**Comment by cleishm** [comment]
Hey @albertoperdomo,

The browser is located at `/browser/` (note the trailing slash). The fix ensures that requests to `/`, requesting HTML, will be redirected correctly to `/browser/`.

Requests to `/browser`, without the trailing slash, will also get redirected, but it's does not honour the X-FORWARD headers. We don't think that needs to be fixed, given that requests shouldn't go there anyway (ideally we'd make it 404, but that's technically tricky).

Can you confirm that requests to `/` and `/browser/` work ok?

Cheers,
Chris

**Comment by albertoperdomo** [comment]
@cleishm Sorry my bad, shouldn't have reviewed after such little sleep.

It does work correctly. The request to `/` redirects to `/browser/` and that request returns the browser UI HTML page correctly.

I do think as well it would be more appropriate to return a 404 rather than just dropping the protocol, but it's certainly not a big issue.

My apologies for wasting your time.

**Comment by cleishm** [comment]
I agree - a 404 would be better (or, indeed, a redirect that honored the headers). The tricky part is that the 'add-a-trailing-slash' redirect is done by the library we use for HTTP, rather than by our own code, and thus it's much harder to manipulate.
