### ISSUE TITLE
Browser - the "Fullscreen" tooltip appears over the button when going back from fullscreen

### ISSUE THREAD

**Issue by gcolbert** [neo4j/neo4j#2247]
There's an annoying glitch regarding the "Fullscreen" tooltip when going back from fullscreen mode: it basically hides the button.

The problem is easy to reproduce:
- click on the "fullscreen" button which is above any result box, it should toggle fullscreen mode
- click on the down arrow to get back from fullscreen mode to normal
- try to click on the "fullscreen" button again: the "Fullscreen" tooltip appears over the button, preventing to go in fullscreen mode more than once per result.

A simple solution would be to remove the tooltip.

**Comment by gcolbert** [comment]
It would be good to fix this, it's almost 1 year old.

**Comment by apcj** [comment]
Hi @gcolbert quite a lots has changed in last few months - it's possible this has been fixed along the way. I just tried and failed to reproduce the problem, but I might not be doing the right thing. Any chance you could try this with 2.2.0-RC1?

**Comment by gcolbert** [comment]
Hi @apcj. Yes, it is fixed with 2.2.0-RC1. I'll just have to wait for the final release, then. Thanks!

**Comment by apcj** [comment]
Thanks for re-testing @gcolbert - much appreciated.

**Comment by jotomo** [comment]
![fullscreen-popup](https://cloud.githubusercontent.com/assets/1732305/10416743/0d80eb70-7023-11e5-95f3-a34aee23478f.png)

I'm still seeing the above. The popup is still there, but isn't blocking any buttons anymore, so it's just a visual glitch at this point. Moving the mouse over the fullscreen button removes the popup (looks like it's on the "mouseOut" event) or when hovering long enough to cause the popup to be shown over the button, removing the old one.
