### ISSUE TITLE
Browser: result window expands on long property values

### ISSUE THREAD

**Issue by mtomala** [neo4j/neo4j#3774]
Neo4j 2.2.0-M02 - browser.

When nodes have properties with long values (text width is greater than result window width) the status block in result window expands horizontally with result window itself so nodes moves outside the screen. 
After that hovered node is no more hovered and status is changed back to "Displaying 25 nodes, 0 relationships" and it shrinks to original size. And after it shrinks and if mouse pointer is in the same place node gets hover again, and so on...

**Comment by oskarhane** [comment]
Thanks @mtomala!
I'll have a look at it.

**Comment by mtomala** [comment]
I'm not sure if it will fix it in all cases, but for me addind those styles helps:
```css
.inspector-footer-row > ul {
   overflow: auto;
}
.view-result-plan, .view-result-graph .graph-holder {
   table-layout: fixed;
}
```

**Comment by oskarhane** [comment]
It's supposed to look like this when property values are long:  
![oskar4j 2015-02-05 at 14 48 02](https://cloud.githubusercontent.com/assets/570998/6061367/7b67ccb6-ad47-11e4-8013-f2c48a161065.png)
![oskar4j 2015-02-05 at 14 48 11](https://cloud.githubusercontent.com/assets/570998/6061368/7b9532d2-ad47-11e4-9b51-872358f9c303.png)

You don't see that overflow indicator (arrow) to the right?

**Comment by mtomala** [comment]
Normally i see that arrow.
Problem occurs on long and unwrappable values.

Try that: 
```
create (n:TestNode {url:'http://that.url.will.be.long.and.without.spaces/?param=iaHR0cDovL3RoYXR1cmwud2lsbGJlLmxvbmcuYW5kLndpdGhvdXRzcGFjZXMuc28vaXR3aWxsL2JlaGFyZC90b3dyYXBpdC9hbmRyZXN1bHQvd2luZG93Lz9uZWVkdG9nZXQ9c29tZW1vcmVzcGFjZSZhbmRsb29rd2hhdGhhcHBlbmVkJnJlcGVhdD1odHRwOi8vdGhhdHVybC53aWxsYmUubG9uZy5hbmQud2l0aG91dHNwYWNlcy5zby9pdHdpbGwvYmVoYXJkL3Rvd3JhcGl0L2FuZHJlc3VsdC93aW5kb3cvP25lZWR0b2dldD1zb21lbW9yZXNwYWNlJmFuZGxvb2t3aGF0aGFwcGVuZWQ='}) return n;
```

![browser-bug-3774](https://cloud.githubusercontent.com/assets/4101758/6062353/5db48148-ad4f-11e4-9d0b-0626a167a397.png)

**Comment by oskarhane** [comment]
Ah, of course. Thanks. I'll fix that.

**Comment by oskarhane** [comment]
This is fixed in master now.

**Comment by mtomala** [comment]
Issue still exists in 2.2.0 in Firefox (v37.0)
It works well in Google Chrome (41.0.2272.118 (64-bit)).
