### ISSUE TITLE
Multiline fields breaking csv loader

### ISSUE THREAD

**Issue by ernestoe** [neo4j/neo4j#5028]
Duplicate of #4434 and #4439 as these are failing again, did it break in 2.2.3? Referred in [StackOverflow](http://stackoverflow.com/questions/31547552/neo4j-load-csv-fails-when-multiline-fields-are-encountered)

**Comment by ernestoe** [comment]
I didn't provide a new example as this one #4434 here proves to be failing. I'm running Community Edition version 2.2.3 in MacOS . This is a non-destructive example

```
LOAD CSV WITH HEADERS FROM 'https://gist.githubusercontent.com/Wiles/4e8b511be7ec9c99bffa/raw/aa289bb63c4f5ee1274071876dc3da22f3016897/gistfile1.txt' as line 
RETURN count(*)
```

gives

```
At https://gist.githubusercontent.com/Wiles/4e8b511be7ec9c99bffa/raw/aa289bb63c4f5ee1274071876dc3da22f3016897/gistfile1.txt:2 - Multi-line fields are illegal in this context and so this might suggest that there's a field with a start quote, but a missing end quote.
```

I created a new issue #5028 for this.

What is key here is the input file. It has multi-lines in the text fields.

This is what the csv file looks like:

```
a,b
1,"Bar"
2,"Bar

Quux
"
3,"Bar

Quux"
```

It is valid according to csv standards.

**Comment by tinwelint** [comment]
Oh, so this is `LOAD CSV` not enabling that option in the csv parser... will fix

**Comment by tinwelint** [comment]
#5050 should fix it

**Comment by ernestoe** [comment]
Version 2.2.4 has solved this issue. Closing.

**Comment by beautifulpage** [comment]
version 3.3.4 and version 3.3.5 still have this problem....
`./neo4j-import   --multiline-fields=true --into ../data/databases/graph.db -nodes ../import/user.csv`

![image](https://user-images.githubusercontent.com/5347165/39241893-ebfc7e88-48ba-11e8-822f-40feb4f7ab71.png)

**Comment by tinwelint** [comment]
Please create a new issue for it, it looks like a separate issue.

**Comment by dterg** [comment]
I get the same error:

![image](https://user-images.githubusercontent.com/18417945/39500535-1d1c6a68-4dad-11e8-88ad-d91dab2a3d51.png)

Going to the actual line number, this looks fine? (I have also replaced any "\n" characters within each line to be "safe"):

![image](https://user-images.githubusercontent.com/18417945/39500498-e040c47c-4dac-11e8-9018-4c13d15aa08b.png)

**Comment by tinwelint** [comment]
@dterg sadly it's a known issue that line numbers aren't always correct.

**Comment by aghogre** [comment]
Same error for me when am trying from Microsoft Azure's neo4j-docker instance: 
"Multi-line fields are illegal in this context and so this might suggest that there's a field with a start quote, but a missing end quote."

It is working fine in my local system neo4j desktop application with win 10 OS.

**Comment by michaelmcmillan** [comment]
Issue here as well.
