### ISSUE TITLE
ExecutionFailure when trying to ORDER BY a list property

### ISSUE THREAD

**Issue by codeseedr** [neo4j/neo4j#9571]
Neo4j version: 2.3.7
Operating system: MacOS X 10.11.6
API/Driver: Java driver v2.3.7

** Steps to reproduce **
```
> CYPHER 2.3 MERGE (n {id: 0}) RETURN n
> CYPHER 2.3 MERGE (n {id: 1, prop: []}) RETURN n
> CYPHER 2.3 MATCH n RETURN n ORDER BY n.prop
```
The last query results in `Neo.DatabaseError.Statement.ExecutionFailure` with no additional explanation of what went wrong. The key bit is that node with id = 0 does not contain the property we are trying to sort with.

** Expected behavior **
Assuming you can't really order by list properties, I'd expect a more descriptive error message, like if we do:
```
> CYPHER 2.3 MERGE (n {id: 0}) SET n.prop = [] RETURN n
> CYPHER 2.3 MATCH n RETURN n ORDER BY n.prop
```
then we get: `Neo.ClientError.Statement.InvalidSyntax` with: Don't know how to compare that. Left: [] (String[]); Right: [] (String[])

**Comment by chrisvest** [comment]
Looks like this is fixed in 3.2.

**Comment by sherfert** [comment]
Thanks for the report. It still occurs when using the rule planner, even on newer versions, though.
