### ISSUE TITLE
Bug - db.schema() returning non-existent relationships

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j#9726]
[Reported](https://neo4j-users.slack.com/archives/C08JCLMV3/p1501180659809695) on User slack channel, on Neo4j 3.2.2, `call db.schema` is showing some relationships that do not exist in the graph. 

Some of the bad relationships seem like they're inferred transitive relationships (`(:a)-[r]->(:b)` exists and `(:b)-[r]->(:c)` exists but `(:a)-[r]->(:c)` doesn't exist in the graph, yet is part of the schema results), or inverted from actual relationships (`(:a)-[r]->(:b)` exists, but `(:b)-[r]->(:a)` does not, yet is part of the schema results).

They also ran `call apoc.meta.graph()` using APOC Procedures, which gives correct results, so something is off specifically in `db.schema()`.

**Comment by GuiDoSignal** [comment]
As agreed on Slack, I am sending some pictures to better clarify this situation.

![2017-07-27_apoc-meta-graph_right](https://user-images.githubusercontent.com/1004193/28689150-f8bd6a2a-72ea-11e7-9e5b-d64f621be2fe.png)
![2017-07-27_db-schema_wrong](https://user-images.githubusercontent.com/1004193/28689149-f8b976ea-72ea-11e7-80db-58209f952644.png)

**Comment by jexp** [comment]
It's a known issue, which I fixed in APOC (but unfortunately it requires sampling the db so it makes it slower). 

The root cause is that the db-statistics only store counts for `(:Label)-[:TYPE]->()` and `()-[:TYPE]->(:Label)` but not the full pattern, so if you add the two together you get some false positives.

In db.schema() there was no one who could take it on, but I can try to fix it there too when I'm back from vacation.

**Comment by davidlrosenblum** [comment]
This bug still exists in 3.3.1.  There is only a straight line relation PART_OF from System to Data Center.  call db.schema 
<img width="530" alt="screen shot 2018-01-08 at 12 39 23 pm" src="https://user-images.githubusercontent.com/21196824/34686298-21756b9c-f479-11e7-88ed-e3322a996356.png">

The schema really looks like this 
![screen shot 2018-01-08 at 3 29 16 pm](https://user-images.githubusercontent.com/21196824/34690867-c62ec250-f488-11e7-81c0-05d9d96858cd.png)

**Comment by benittes** [comment]
This bug still exists in 3.3.4
**db.schema**
![neo4j-3-3-4-call-db-schema](https://user-images.githubusercontent.com/2580069/38859723-90b399d4-4226-11e8-8e76-b63d74ba0469.png)
**apoc.meta.graph**
![neo4j-3-3-4-call-db-apoc-meta-graph](https://user-images.githubusercontent.com/2580069/38859778-a98fc126-4226-11e8-83d8-d75072e382eb.png)

**Comment by ThomPatterson** [comment]
I'm seeing this bug in 3.4.0 beta 02 as well.

**Comment by jhb** [comment]
The bug still exists in 3.3.5 community. If there is no time to fix the bug, maybe it could be mentioned in the documentation?

**Comment by micuncang** [comment]
The bug still exists in 3.4.7 community. VERY Confusing

**Comment by rmasrani** [comment]
Still here.

**Comment by vjramirez** [comment]
![image](https://user-images.githubusercontent.com/24277356/51613308-79d79a00-1f23-11e9-83a9-caf146273827.png)
Version 3.5.1, same bug.

**Comment by gparissis** [comment]
3.5.3 same bug.

**Comment by ghost** [comment]
3.5.5. same issue

**Comment by hfmm99** [comment]
Still existing on Neo4j 3.5.7

**Comment by ghost** [comment]
Still exists. also only returns 2 labels from my db of dozens of labels, not really useful unless it really returns the defined labels. I also tried apoc.meta.subgraph({ labels:[list_of_all_known_labels]}) which still returned only two of the labels.

**Comment by srgamalial** [comment]
> It's a known issue, which I fixed in APOC (but unfortunately it requires sampling the db so it makes it slower).
> 
> The root cause is that the db-statistics only store counts for `(:Label)-[:TYPE]->()` and `()-[:TYPE]->(:Label)` but not the full pattern, so if you add the two together you get some false positives.
> 
> In db.schema() there was no one who could take it on, but I can try to fix it there too when I'm back from vacation.

@jexp It is still there and its messing up our datamodel software which uses db.schema(). Why don't we retire this if we cannot fix it and enforce apoc usage only please?

**Comment by ghost** [comment]
@srgamalial Does the apoc version work for you? I do not get accurate results.

**Comment by simonalexander2005** [comment]
The same issue exists in 4.0.0

**Comment by i4never** [comment]
It's misleading. I've spend much time checking my source data.

**Comment by lawrencerowland** [comment]
Im experiencing this (I confess I'm still in 3.5.14)

**Comment by freefallzhou** [comment]
meet same bug, so sad

**Comment by stefanak-michal** [comment]
Neo4j/4.1.3 still contains this problem

**Comment by Zilig** [comment]
> At first i was very excited to see this function. After trying it, I was confused, i want to say, so sad!

**Comment by tdoan2010** [comment]
Is there any news? Version 4.2.4 still has this bug.

**Comment by aabrodskiy** [comment]
4.3.2 bug is still there. it's very confusing and I wasted so much time trying to troubleshoot what was going wrong with relationships, while in fact nothing was wrong.

**Comment by palanquinpeace** [comment]
Many thanks in advance to the folks who resolve this. I am quite grateful to know this is a bug and not my cypher. I did spend time trying to troubleshoot, but I don't consider it time wasted...not entirely wasted, anyway :)   especially since adding this comment motivated me to join github.  Blessings all!

**Comment by Otterpohl** [comment]
4.3.6 and unfortunately the bug is still there 😢

**Comment by TheMellyBee** [comment]
Neo4j Aura version 4 this still exists. What is the apoc that works right now?

**Comment by rikveenboer** [comment]
> Neo4j Aura version 4 this still exists. What is the apoc that works right now?

[CALL apoc.meta.graph()](https://neo4j.com/labs/apoc/4.1/overview/apoc.meta/apoc.meta.graph/)

**Comment by ghost** [comment]
@jexp Can you weigh in on this problem. It would be very useful to output an accurate and reliable schema graph.

**Comment by AurelienData** [comment]
> > Neo4j Aura version 4 this still exists. What is the apoc that works right now?

For me, this method works `CALL apoc.meta.graph()` in contrary of `CALL db.schema.visualization`

<img width="1348" alt="good" src="https://user-images.githubusercontent.com/95886578/145481570-99879cf7-209a-43fa-bc56-3020a9545c58.png">

<img width="1345" alt="wrong" src="https://user-images.githubusercontent.com/95886578/145481597-5edfd1dc-be39-4c0b-b0b4-9fa0f46584f0.png">

**Comment by jexp** [comment]
I can't say much except that it's been long known and we fixed it in apoc many years ago.

The solutions is to post-validate after getting the unioned information from the database statistics to see which relationships are false positives.

Of course that makes the apoc version a bit slower but more correct (you can also configure the sample size to make it faster again).

There are also

* apoc.meta.data
* apoc.meta.schema
* and many more useful procs in the meta package

https://neo4j.com/labs/apoc/4.1/overview/apoc.meta/

**Comment by gem-neo4j** [comment]
Hi! The description of db.schema.visualization has been updated to be a bit more descriptive:

"Visualizes the schema of the data based on available statistics. A new node is returned for each label. The properties represented on the node include: `name` (label name), `indexes` (list of indexes), and `constraints` (list of constraints). A relationship of a given type is returned for all possible combinations of start and end nodes. Note that this may include additional relationships that do not exist in the data due to the information available in the count store. "

There have also been some fixes applied to the apoc.meta.graph procedure, as the sampling was not working as expected. Allowing the sampling to now be used as intended. This should allow the sampling in the APOC procedure to be either accurate (removes all non-exisiting relationships by doing a full scan, no sampling) or using sampling, the result will be faster, but potentially less accurate.

**Comment by arwentwinkle** [comment]
How is this not fixed yet? 
Is there a fix on the roadmap?

**Comment by jordus100** [comment]
This is insane, the latest 2025.11.2 version of Neo4J still has this extremely confusing bug.

**Comment by hvub** [comment]
`db.schema.visualization` is designed to not query the graph but only metadata available in the store. This makes the procedure very efficient.

Unfortunately, said metadata available in the store does not have information about `(n:SLabel)-[r:Type]->(n:TLabel)` combinations, but only about `(n:SLabel)-[r:Type]->()` and `()-[r:Type]->(n:TLabel)` combinations. The procedure multiplies the latter to get the former. Yes, that produces false positives, but it avoids queries the graph. It is a tradeoff.

As a workaround, you can do the querying of the graph yourself. Here is a toy example.

Assume that is graph:

```
CREATE (:A)-[:R]->(:B), (:C)-[:R]->(:D)
```

The vanilla call

```
CALL db.schema.visualization() YIELD nodes, relationships
```

gives

<img width="395" height="393" alt="Image" src="https://github.com/user-attachments/assets/2da80f5e-5249-4497-9e74-ba2bcbdf1e4d" />

which wrongly shows relationships `(:A)-[:R]->(:D)` and `(:C)-[:R]->(:B)`.

With some post filtering

```
CYPHER 25
CALL db.schema.visualization() YIELD nodes, relationships
CALL (relationships) {
  UNWIND relationships AS r
  LET sl = head(labels(startNode(r))), rt = type(r), el = head(labels(endNode(r)))
  FILTER EXISTS { (:$(sl))-[:$(rt)]->(:$(el)) }
  RETURN COLLECT(r) AS relationshipsFiltered
}
RETURN nodes, relationshipsFiltered
```

the result is this

<img width="395" height="393" alt="Image" src="https://github.com/user-attachments/assets/c50518fd-3277-4b9c-8cc7-fe26efb36b9e" />

The wrong relationships `(:A)-[:R]->(:D)` and `(:C)-[:R]->(:B)` are gone. 🎉
